# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  # - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - "/vendor/"

# Site settings
title: SecAI Lab @ Sungkyunkwan University
subtitle: ""
email: kevin.koo@g.skku.edu
domain: "secai.skku.edu"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://secai.skku.edu/"  # the base hostname & protocol for your site
cover: "/assets/cover-skku.jpg"
logo: "/assets/image.png"

# Build settings
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
# pagination:
#   enabled: true
#   per_page: 4
#   permalink: "/posts/page:num/"
#   sort_reverse: true

# permalink: "/:title/"
# Archive settings (see https://github.com/jekyll/jekyll-archives/)

