#!/usr/bin/env python3
"""Regenerate deadlines/data/conferences/<year>/<category>.yml from upstream trackers.

Sources (see deadlines/scripts/conferences.yml for the per-venue mapping):
  * ccfddl/ccf-deadlines  - one YAML file per conference on GitHub (multi-year history)
  * sec-deadlines.github.io - single _data/conferences.yml (latest edition only)

Merge policy (per target venue and edition year):
  * no upstream record            -> the existing repo entry is kept byte-for-byte
  * upstream record exists        -> upstream wins for deadline / abstract_deadline /
    timezone / place / date / link (only where upstream has a real, non-TBA value);
    start / end are re-derived from the winning date string when it parses, so they
    can never contradict it; the existing entry always wins for tier, note, id,
    full_name, type
  * existing entries are never deleted; manual.yml (frontend priority 0) is never touched
  * safety rail: an existing concrete FUTURE deadline is never moved by more than
    90 days by upstream data - such candidates are ignored with a warning

Usage:
  python3 deadlines/scripts/update_deadlines.py            # update files in place
  python3 deadlines/scripts/update_deadlines.py --dry-run  # print changes only

Exit codes: 0 = success (with or without changes), 1 = fatal (config unreadable,
every upstream source unreachable, ...). Nothing is written on a fatal error.
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = Path(__file__).resolve().parent / "conferences.yml"
DATA_DIR = REPO_ROOT / "deadlines" / "data" / "conferences"

CATEGORIES = ["system", "software", "security", "ai"]
TODAY = dt.date.today()
FROM_YEAR = TODAY.year - 2  # same window as deadlines/assets/deadline-tracker.js
TO_YEAR = TODAY.year + 1

CCFDDL_RAW = "https://raw.githubusercontent.com/ccfddl/ccf-deadlines/main/conference/"
SECDL_RAW = ("https://raw.githubusercontent.com/sec-deadlines/"
             "sec-deadlines.github.io/master/_data/conferences.yml")

HEADER = (
    "# AUTO-GENERATED by deadlines/scripts/update_deadlines.py — do not edit by hand.\n"
    "# Human corrections belong in deadlines/data/manual.yml (it overrides this file).\n"
    "# Sources: ccfddl/ccf-deadlines, sec-deadlines.github.io "
    "(mapping: deadlines/scripts/conferences.yml)\n"
)

DEADLINE_RE = re.compile(r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$")
TIMEZONE_RE = re.compile(r"^(AoE|PST|PDT|UTC([+-]\d{1,2})?|[A-Za-z]+(/[A-Za-z0-9_+\-]+)+)$")
# ccfddl timeline entries that are not paper-submission cycles (pre-2024 legacy).
SKIP_COMMENT_RE = re.compile(r"abstract|registration|notification|camera[ -]?ready|workshop", re.I)
FIELD_ORDER = ["title", "year", "id", "full_name", "type", "tier", "link",
               "abstract_deadline", "deadline", "timezone", "place", "date",
               "start", "end", "note"]
SAFETY_RAIL_DAYS = 90

warnings: list[str] = []
actions: list[tuple[str, str]] = []  # (action, description)


def warn(msg: str) -> None:
    warnings.append(msg)


def as_list(value):
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def clean(value) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


# --------------------------------------------------------------------------- fetch

def http_get(url: str, timeout: int = 30, retries: int = 2) -> str:
    last = None
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "secai-lab-deadline-updater/1.0"})
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return resp.read().decode("utf-8")
        except Exception as exc:  # noqa: BLE001 - any network error is retryable
            last = exc
            if attempt < retries:
                time.sleep(2 * (attempt + 1))
    raise RuntimeError(f"{url}: {last}")


# --------------------------------------------------------------------- conversion

def norm_dt(value):
    """Normalize an upstream deadline value to 'YYYY-MM-DD HH:MM' (or None)."""
    if value is None:
        return None
    if isinstance(value, dt.datetime):
        return value.strftime("%Y-%m-%d %H:%M")
    if isinstance(value, dt.date):
        return None  # date-only values carry no usable time - skip
    s = str(value).strip()
    if not s or s.upper() in ("TBD", "TBA"):
        return None
    m = re.match(r"^(\d{4})-(\d{1,2})-(\d{1,2})[ T](\d{1,2}):(\d{2})(?::\d{2})?$", s)
    if not m:
        return None
    y, mo, d, h, mi = m.groups()
    return f"{int(y):04d}-{int(mo):02d}-{int(d):02d} {int(h):02d}:{mi}"


def none_if_tba(value):
    s = clean(value)
    if not s or s.upper() in ("TBD", "TBA"):
        return None
    return s


def map_ccfddl_tz(value):
    s = clean(value)
    if not s:
        return None
    if s == "AoE":
        return "AoE"
    if s in ("UTC", "UTC+0"):
        return "UTC+0"
    if s == "PT":
        return "PST"
    if re.fullmatch(r"UTC[+-]\d{1,2}", s):
        return s
    return None


def map_secdl_tz(value):
    s = clean(value)
    if not s:
        return "AoE"  # documented sec-deadlines convention: absent = AoE
    m = re.fullmatch(r"Etc/GMT([+-])(\d{1,2})", s)
    if m:  # NOTE: Etc/GMT signs are inverted (Etc/GMT+8 == UTC-8)
        return "UTC" + ("-" if m.group(1) == "+" else "+") + m.group(2)
    if s in ("Etc/GMT", "Etc/UTC", "UTC"):
        return "UTC+0"
    return s  # IANA names pass through; the frontend parses them


def convert_ccfddl(doc, key):
    """ccfddl per-conference file -> {year: candidate}."""
    out = {}
    if not isinstance(doc, list) or not doc:
        warn(f"ccfddl {key}: unexpected file structure, skipped")
        return out
    if len(doc) > 1:
        warn(f"ccfddl {key}: {len(doc)} records in file, using the first")
    for conf in doc[0].get("confs") or []:
        year = conf.get("year")
        if not isinstance(year, int) or not FROM_YEAR <= year <= TO_YEAR:
            continue
        deadlines, abstracts = [], []
        for entry in conf.get("timeline") or []:
            comment = clean(entry.get("comment"))
            if SKIP_COMMENT_RE.search(comment):
                warn(f"ccfddl {key} {year}: skipped non-cycle timeline entry ({comment!r})")
                continue
            deadline = norm_dt(entry.get("deadline"))
            if deadline is None:
                continue  # TBD / unparsable cycle
            deadlines.append(deadline)
            abstracts.append(norm_dt(entry.get("abstract_deadline")))
        if not deadlines:
            continue
        link = clean(conf.get("link"))
        out[year] = {
            "deadlines": deadlines,
            "abstracts": abstracts,
            "timezone": map_ccfddl_tz(conf.get("timezone")),
            "place": none_if_tba(conf.get("place")),
            "date": none_if_tba(conf.get("date")),
            "link": link if link.startswith("http") else None,
            "source": "ccfddl",
        }
    return out


def convert_secdl(records, locator, key):
    """sec-deadlines record -> {year: candidate} (latest edition only)."""
    if isinstance(locator, str):
        locator = {"name": locator}
    name, needle = locator.get("name"), clean(locator.get("description_contains"))
    matches = [r for r in records
               if clean(r.get("name")) == name
               and (not needle or needle.lower() in clean(r.get("description")).lower())]
    if not matches:
        warn(f"secdl {key}: no record named {name!r}")
        return {}
    if len(matches) > 1:
        warn(f"secdl {key}: {len(matches)} ambiguous records named {name!r}, skipped")
        return {}
    rec = matches[0]
    year = rec.get("year")
    if not isinstance(year, int) or not FROM_YEAR <= year <= TO_YEAR:
        return {}
    deadlines = []
    for value in as_list(rec.get("deadline")):
        s = str(value).replace("%Y", str(year - 1)).replace("%y", str(year))
        deadline = norm_dt(s)
        if deadline is not None:
            deadlines.append(deadline)
    if not deadlines:
        return {}
    abstracts = [norm_dt(a) for a in as_list(rec.get("abstract_deadline"))]
    abstracts = (abstracts + [None] * len(deadlines))[:len(deadlines)]
    date = none_if_tba(rec.get("date"))
    if date and not re.search(r"\d{4}", date):
        date = f"{date}, {year}"  # sec-deadlines dates usually omit the year
    link = clean(rec.get("link"))
    return {year: {
        "deadlines": deadlines,
        "abstracts": abstracts,
        "timezone": map_secdl_tz(rec.get("timezone")),
        "place": none_if_tba(rec.get("place")),
        "date": date,
        "link": link if link.startswith("http") else None,
        "source": "secdl",
    }}


# ------------------------------------------------------------------ existing data

def split_blocks(text: str):
    """Split a YAML list file into raw per-record text blocks."""
    lines = text.split("\n")
    starts = [i for i, line in enumerate(lines) if line.startswith("- ")]
    blocks = []
    for j, start in enumerate(starts):
        end = starts[j + 1] if j + 1 < len(starts) else len(lines)
        blocks.append("\n".join(lines[start:end]).rstrip())
    return blocks


def match_target(title: str, targets):
    """Same alias-matching rule as matchTarget() in deadline-tracker.js."""
    ht = clean(title).lower()
    if not ht:
        return None
    for target in targets:
        for alias in target.get("aliases") or [target["key"]]:
            a = str(alias).lower()
            if ht == a or ht.startswith(a + " ") or f" {a} " in ht or ht.endswith(" " + a):
                return target
    return None


def load_existing():
    """-> {(year, category): {'path', 'text', 'items'}}; item = {'data','raw',...}."""
    files = {}
    for year in range(FROM_YEAR, TO_YEAR + 1):
        for cat in CATEGORIES:
            path = DATA_DIR / str(year) / f"{cat}.yml"
            entry = {"path": path, "text": None, "items": []}
            files[(year, cat)] = entry
            if not path.exists():
                continue
            text = path.read_text(encoding="utf-8")
            entry["text"] = text
            try:
                data = yaml.safe_load(text)
            except yaml.YAMLError as exc:
                warn(f"{path}: YAML parse error ({exc}); file left untouched")
                entry["broken"] = True
                continue
            data = data if isinstance(data, list) else []
            blocks = split_blocks(text)
            if len(blocks) != len(data):
                warn(f"{path}: {len(data)} records vs {len(blocks)} text blocks; "
                     "byte-level round-trip unavailable, formatting will be regenerated")
                blocks = [None] * len(data)
            for rec, raw in zip(data, blocks):
                if isinstance(rec, dict):
                    entry["items"].append({"data": rec, "raw": raw, "new_data": None})
    return files


# ------------------------------------------------------------------------- merge

def canon_tz(value):
    s = clean(value)
    if s == "AoE":
        return "UTC-12"
    if s in ("UTC", "UTC+0"):
        return "UTC+0"
    return s


def canon_deadline_field(value):
    values = [norm_dt(v) or (str(v) if v is not None else None) for v in as_list(value)]
    while values and values[-1] is None:
        values.pop()
    return tuple(values)


def canon_record(rec):
    """Comparison form: equates scalar/list, 23:59:59/23:59, AoE/UTC-12, null/absent."""
    out = {}
    for key, value in rec.items():
        if value is None or key == "tba":
            continue
        if key in ("deadline", "abstract_deadline"):
            if canon_deadline_field(value):
                out[key] = canon_deadline_field(value)
        elif key == "timezone":
            out[key] = canon_tz(value)
        elif key in ("start", "end"):
            out[key] = str(value)
        else:
            out[key] = value
    return out


MONTH_NAMES = ["january", "february", "march", "april", "may", "june", "july",
               "august", "september", "october", "november", "december"]
DATE_RANGE_RE = re.compile(
    r"^([A-Za-z.]+)\s*(\d{1,2})\s*(?:-\s*([A-Za-z.]+)?\s*(\d{1,2}))?\s*,?\s*(\d{4})\.?$")


def month_num(token):
    t = clean(token).lower().strip(".")
    if len(t) < 3:
        return None
    for i, name in enumerate(MONTH_NAMES, 1):
        if name.startswith(t):
            return i
    return None


def parse_date_range(value):
    """'April 13-16, 2026' / 'March 30 - April 2, 2027' / 'Dec 7, 2026' ->
    (start_date, end_date), or None when the format is not understood."""
    s = clean(value).replace("–", "-").replace("—", "-").replace("−", "-")
    m = DATE_RANGE_RE.match(s)
    if not m:
        return None
    mon1_tok, day1, mon2_tok, day2, year = m.groups()
    mon1 = month_num(mon1_tok)
    mon2 = month_num(mon2_tok) if mon2_tok else mon1
    if mon1 is None or mon2 is None:
        return None
    try:
        start = dt.date(int(year), mon1, int(day1))
        end = dt.date(int(year), mon2, int(day2)) if day2 else start
        if end < start:  # range wraps into the next calendar year
            end = dt.date(int(year) + 1, mon2, int(day2))
    except ValueError:
        return None
    return start, end


def parse_dl_date(value):
    m = re.match(r"^(\d{4})-(\d{1,2})-(\d{1,2})", str(value or ""))
    if not m:
        return None
    try:
        return dt.date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    except ValueError:
        return None


def rail_triggered(existing, cand_deadlines):
    """True if upstream would move a concrete future deadline by > 90 days."""
    if not existing:
        return False
    future = [d for d in (parse_dl_date(v) for v in as_list(existing.get("deadline")))
              if d is not None and d >= TODAY]
    cand = [d for d in (parse_dl_date(v) for v in cand_deadlines) if d is not None]
    if not future or not cand:
        return False
    return any(min(abs((c - d).days) for c in cand) > SAFETY_RAIL_DAYS for d in future)


def norm_kept_deadlines(value):
    """Normalize deadline values kept from an existing record (strip :SS)."""
    if isinstance(value, list):
        return [norm_dt(v) or v for v in value]
    if value is None:
        return None
    return norm_dt(value) or value


def build_merged(target, year, existing, cand):
    """Apply the merge policy; returns (merged_record, railed)."""
    merged = dict(existing) if existing else {}
    merged["title"] = target["key"]
    merged["year"] = year
    if not existing:
        merged["id"] = f"{target['slug']}{year % 100:02d}"
        merged["full_name"] = target["full_name"]
        merged["type"] = target.get("type", "conference")
        if target.get("tier"):
            merged["tier"] = target["tier"]
    for field in ("link", "place", "date"):
        if cand.get(field):
            merged[field] = cand[field]
    if (existing and cand.get("date") and clean(existing.get("date")).upper() not in ("", "TBA")):
        old_range, new_range = parse_date_range(existing["date"]), parse_date_range(cand["date"])
        if old_range and new_range and old_range != new_range:
            warn(f"CONFERENCE DATE CHANGED {target['key']} {year}: "
                 f"{existing['date']!r} -> {cand['date']!r} (source {cand['source']}) "
                 "- verify against the official page; override in manual.yml if upstream is wrong")
    if cand.get("date"):
        # Keep start/end consistent with the (upstream-won) date string.
        parsed = parse_date_range(cand["date"])
        if parsed:
            merged["start"], merged["end"] = parsed
    railed = rail_triggered(existing, cand["deadlines"])
    if railed:
        warn(f"SAFETY RAIL {target['key']} {year}: upstream ({cand['source']}) would move a "
             f"future deadline by > {SAFETY_RAIL_DAYS} days "
             f"({as_list(existing.get('deadline'))} -> {cand['deadlines']}); kept existing")
    else:
        merged["deadline"] = (cand["deadlines"][0] if len(cand["deadlines"]) == 1
                              else list(cand["deadlines"]))
        if any(cand["abstracts"]):
            abstracts = (cand["abstracts"] + [None] * len(cand["deadlines"]))[:len(cand["deadlines"])]
            merged["abstract_deadline"] = abstracts[0] if len(abstracts) == 1 else abstracts
        # else: the existing abstract_deadline (if any) stays untouched
        if cand.get("timezone") and canon_tz(cand["timezone"]) != canon_tz(merged.get("timezone")):
            merged["timezone"] = cand["timezone"]
    merged["deadline"] = norm_kept_deadlines(merged.get("deadline"))
    merged["abstract_deadline"] = norm_kept_deadlines(merged.get("abstract_deadline"))
    if merged["abstract_deadline"] is None:
        merged.pop("abstract_deadline")
    merged.pop("tba", None)  # legacy flag: meaningless once a record has real data
    if merged.get("timezone") == "TBA":
        merged.pop("timezone")
    return merged, railed


def validate(rec, canonical_keys):
    errors = []
    if rec.get("title") not in canonical_keys:
        errors.append(f"title {rec.get('title')!r} is not a canonical key")
    year = rec.get("year")
    if not isinstance(year, int) or not FROM_YEAR <= year <= TO_YEAR:
        errors.append(f"year {year!r} outside {FROM_YEAR}..{TO_YEAR}")
    deadlines = [d for d in as_list(rec.get("deadline")) if d is not None]
    if not deadlines:
        errors.append("no concrete deadline")
    errors += [f"bad deadline {d!r}" for d in deadlines if not DEADLINE_RE.match(str(d))]
    errors += [f"bad abstract_deadline {a!r}" for a in as_list(rec.get("abstract_deadline"))
               if a is not None and not DEADLINE_RE.match(str(a))]
    tz = rec.get("timezone")
    if tz is not None and not TIMEZONE_RE.match(str(tz)):
        errors.append(f"bad timezone {tz!r}")
    link = rec.get("link")
    if link is not None and not re.match(r"^https?://", str(link)):
        errors.append(f"bad link {link!r}")
    return errors


# ---------------------------------------------------------------------- emission

def yaml_quote(value) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_scalar(key, value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, (dt.datetime, dt.date)):
        return value.strftime("%Y-%m-%d")
    s = str(value)
    if key in ("id", "link", "timezone", "start", "end", "type"):
        return s
    if key == "tier" and re.fullmatch(r"T\d", s):
        return s
    return yaml_quote(s)


def render_record(rec) -> str:
    keys = [k for k in FIELD_ORDER if k in rec] + [k for k in rec if k not in FIELD_ORDER]
    lines = []
    for key in keys:
        value = rec[key]
        if value is None:
            continue
        prefix = "- " if not lines else "  "
        if key in ("deadline", "abstract_deadline") and isinstance(value, list):
            lines.append(f"{prefix}{key}:")
            lines += ["    - " + ("null" if item is None else yaml_quote(item)) for item in value]
        else:
            lines.append(f"{prefix}{key}: {render_scalar(key, value)}")
    return "\n".join(lines)


def assemble_file(items) -> str:
    blocks = sorted(items, key=lambda it: str(it["sort_title"]))
    return HEADER + "\n" + "\n\n".join(b["text"] for b in blocks) + "\n"


# -------------------------------------------------------------------------- main

def load_config():
    cfg = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    targets = cfg["conferences"]
    default_priority = (cfg.get("defaults") or {}).get("source_priority") or ["secdl", "ccfddl"]
    for target in targets:
        sources = target.get("sources")
        target["sources"] = sources if isinstance(sources, dict) else {}
        priority = target.get("source_priority") or default_priority
        target["priority"] = [s for s in priority if s in target["sources"]]
    return targets


def fetch_upstream(targets):
    """-> ({source: {key: {year: candidate}}}, failed, status_lines, any_source_ok).

    `failed` maps source name -> set of target keys whose fetch from that source
    FAILED (network/parse error), as opposed to succeeded-but-has-no-record.
    The merge loop must never fall back past a failed higher-priority source:
    stale lower-priority data would clobber values the failed source owns.
    """
    data = {"ccfddl": {}, "secdl": {}}
    failed = {"ccfddl": set(), "secdl": set()}
    status = []

    ccfddl_targets = [t for t in targets if "ccfddl" in t["sources"]]
    ok = 0
    for target in ccfddl_targets:
        path = target["sources"]["ccfddl"]
        url = CCFDDL_RAW + urllib.parse.quote(path)
        try:
            doc = yaml.safe_load(http_get(url))
            data["ccfddl"][target["key"]] = convert_ccfddl(doc, target["key"])
            ok += 1
        except Exception as exc:  # noqa: BLE001
            failed["ccfddl"].add(target["key"])
            warn(f"ccfddl fetch failed for {target['key']} ({path}): {exc}")
    status.append(f"ccfddl: {ok}/{len(ccfddl_targets)} conference files fetched")
    ccfddl_ok = ok > 0

    secdl_ok = False
    try:
        records = yaml.safe_load(http_get(SECDL_RAW))
        if not isinstance(records, list):
            raise RuntimeError("unexpected structure (not a list)")
        for target in targets:
            if "secdl" in target["sources"]:
                data["secdl"][target["key"]] = convert_secdl(
                    records, target["sources"]["secdl"], target["key"])
        status.append(f"secdl: ok ({len(records)} records)")
        secdl_ok = True
    except Exception as exc:  # noqa: BLE001
        failed["secdl"] = {t["key"] for t in targets if "secdl" in t["sources"]}
        warn(f"secdl fetch failed: {exc}")
        status.append("secdl: FAILED")

    return data, failed, status, (ccfddl_ok or secdl_ok)


def sources_disagree(a, b):
    """True if two candidates for the same edition differ materially (> 1 day on
    any cycle, or a different cycle count). 1-day tolerance absorbs equivalent
    instants encoded in different timezones (e.g. AoE vs UTC)."""
    da = sorted(d for d in (parse_dl_date(v) for v in a["deadlines"]) if d)
    db = sorted(d for d in (parse_dl_date(v) for v in b["deadlines"]) if d)
    if len(da) != len(db):
        return True
    return any(abs((x - y).days) > 1 for x, y in zip(da, db))


def cross_fill_abstracts(winner, others):
    """Adopt the losing source's abstract deadlines when cycles line up exactly."""
    if any(winner["abstracts"]):
        return
    for other in others:
        if (len(other["deadlines"]) == len(winner["deadlines"]) and any(other["abstracts"])
                and all(o[:10] == w[:10] for o, w in zip(other["deadlines"], winner["deadlines"]))):
            winner["abstracts"] = list(other["abstracts"])
            return


def describe_changes(old, new):
    changes = []
    for key in sorted(set(old) | set(new)):
        if old.get(key) != new.get(key):
            changes.append(f"{key}: {old.get(key)!r} -> {new.get(key)!r}")
    return changes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dry-run", action="store_true",
                        help="print the would-be changes without writing files")
    args = parser.parse_args()

    try:
        targets = load_config()
    except Exception as exc:  # noqa: BLE001
        print(f"FATAL: cannot load {CONFIG_PATH}: {exc}")
        return 1
    canonical_keys = {t["key"] for t in targets}

    upstream, failed_fetches, fetch_status, any_ok = fetch_upstream(targets)
    if not any_ok:
        print("\n".join(fetch_status))
        print("FATAL: every upstream source failed; nothing written.")
        return 1

    files = load_existing()

    # Index existing records by (canonical key, edition year).
    index = {}
    for (year, cat), entry in files.items():
        for item in entry["items"]:
            rec = item["data"]
            target = match_target(rec.get("title") or rec.get("name"), targets)
            rec_year = rec.get("year") if isinstance(rec.get("year"), int) else year
            item["bucket"] = (year, cat)
            item["target_key"] = target["key"] if target else None
            if target:
                if (target["key"], rec_year) in index:
                    warn(f"duplicate record for {target['key']} {rec_year} in repo data; "
                         "only the first copy is auto-updated")
                else:
                    index[(target["key"], rec_year)] = item

    # Merge upstream candidates into existing records / create new ones.
    new_items = []
    kept, updated, created = [], [], []
    for target in targets:
        # Never fall back past a source whose FETCH failed (vs. has no record):
        # its stale lower-priority sibling must not clobber data it owns.
        usable = []
        for src in target["priority"]:
            if target["key"] in failed_fetches.get(src, set()):
                if usable or len(target["priority"]) > 1:
                    warn(f"{target['key']}: source '{src}' unavailable this run; "
                         "not falling back to lower-priority sources (existing data kept)")
                break
            usable.append(src)
        per_source = {src: upstream.get(src, {}).get(target["key"], {}) for src in usable}
        years = sorted({y for cands in per_source.values() for y in cands})
        for year in years:
            ordered = [per_source[src][year] for src in usable if year in per_source[src]]
            winner = dict(ordered[0])
            for other in ordered[1:]:
                if sources_disagree(winner, other):
                    warn(f"CROSS-SOURCE DISAGREEMENT {target['key']} {year}: "
                         f"{winner['source']}={winner['deadlines']} vs "
                         f"{other['source']}={other['deadlines']}; using {winner['source']} "
                         "- verify against the official CFP")
            cross_fill_abstracts(winner, ordered[1:])
            item = index.get((target["key"], year))
            existing = item["data"] if item else None
            merged, railed = build_merged(target, year, existing, winner)
            errors = validate(merged, canonical_keys)
            if errors:
                warn(f"validation failed for {target['key']} {year} "
                     f"({'; '.join(errors)}); kept existing entry" if existing
                     else f"validation failed for new {target['key']} {year} "
                          f"({'; '.join(errors)}); record dropped")
                continue
            if existing is not None:
                if canon_record(merged) == canon_record(existing):
                    kept.append(f"{target['key']} {year}")
                else:
                    item["new_data"] = merged
                    changes = describe_changes(canon_record(existing), canon_record(merged))
                    label = " [RAILED]" if railed else ""
                    updated.append(f"{target['key']} {year} ({winner['source']}){label}: "
                                   + "; ".join(changes))
            else:
                created.append(f"{target['key']} {year} ({winner['source']}) -> "
                               f"{year}/{target['category']}.yml")
                new_items.append({"bucket": (year, target["category"]),
                                  "record": merged, "sort_title": merged["title"]})

    # Existing matched records with no upstream candidate are implicitly kept.
    for (key, year), item in sorted(index.items()):
        if item["new_data"] is None and f"{key} {year}" not in kept:
            has_candidate = any(year in upstream.get(src, {}).get(key, {})
                                for src in ("ccfddl", "secdl"))
            if not has_candidate:
                kept.append(f"{key} {year} (no upstream)")

    # Assemble output files.
    results = []  # (path, old_text, new_text)
    for (year, cat), entry in sorted(files.items()):
        if entry.get("broken"):
            continue
        blocks = []
        for item in entry["items"]:
            rec = item["new_data"] or item["data"]
            if item["new_data"] is not None or item["raw"] is None:
                text = render_record(rec)
            else:
                text = item["raw"]  # byte-level round-trip for untouched records
            blocks.append({"text": text, "sort_title": rec.get("title") or ""})
        for item in new_items:
            if item["bucket"] == (year, cat):
                blocks.append({"text": render_record(item["record"]),
                               "sort_title": item["sort_title"]})
        if not blocks:
            continue  # never write empty files
        new_text = assemble_file(blocks)
        if new_text != entry["text"]:
            results.append((entry["path"], entry["text"], new_text))

    # ------------------------------------------------------------------ summary
    print("== Fetch status ==")
    print("\n".join(fetch_status))
    print(f"\n== Actions ({FROM_YEAR}..{TO_YEAR}) ==")
    for line in created:
        print(f"  new      {line}")
    for line in updated:
        print(f"  updated  {line}")
    print(f"  kept     {len(kept)}: {', '.join(sorted(kept))}")
    if warnings:
        print("\n== Warnings ==")
        for line in warnings:
            print(f"  {line}")
    print("\n== Files ==")
    if not results:
        print("  no file changes")
    for path, old_text, new_text in results:
        rel = path.relative_to(REPO_ROOT)
        state = "create" if old_text is None else "update"
        if args.dry_run:
            print(f"  would {state} {rel} ({len(new_text.splitlines())} lines)")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            tmp = path.with_name(path.name + ".tmp")
            tmp.write_text(new_text, encoding="utf-8")
            os.replace(tmp, path)  # atomic: a crash mid-write can't truncate live data
            print(f"  {state}d {rel} ({len(new_text.splitlines())} lines)")
    if args.dry_run:
        print("\n(dry run: nothing was written)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
