#!/usr/bin/env python3
"""Regenerate deadlines/data/conferences/<year>/<category>.yml from upstream trackers.

Sources (see deadlines/scripts/conferences.yml for the per-venue mapping):
  * ccfddl/ccf-deadlines  - one YAML file per conference on GitHub (multi-year history)
  * sec-deadlines.github.io - single _data/conferences.yml (latest edition only)

Merge policy (per target venue and edition year):
  * no upstream record            -> the existing repo entry is kept (byte-for-byte
    unless the normalization rules below change it)
  * upstream record exists        -> upstream wins for deadline / abstract_deadline /
    timezone / place / date / link (only where upstream has a real, non-TBA value);
    start / end are re-derived from the winning date string when it parses, and
    dropped when it does not, so they never contradict it
  * manual.yml overrides beat upstream on every field they set, in either
    direction, and are propagated into the generated files on every run so the
    frontend's two sources always agree; manual.yml itself is never written
  * conferences.yml owns title / id / full_name / type / tier: they are enforced
    on current and future editions (past editions keep their historical values)
  * records are re-filed into the year/category bucket conferences.yml assigns
  * a placeholder note ("CFP not announced yet", ...) is cleared automatically
    the moment the record gains its first concrete deadline
  * existing entries are never deleted
  * safety rail: an existing concrete FUTURE deadline is never moved by more than
    90 days by upstream data - such records are kept untouched and the run is
    marked degraded for human review

Usage:
  python3 deadlines/scripts/update_deadlines.py            # update files in place
  python3 deadlines/scripts/update_deadlines.py --dry-run  # print changes only

Exit codes: 0 = healthy (with or without changes); 2 = degraded - files were
still written where safe, but something needs human attention (a source fetch
failed or changed shape, validation rejected a record, the safety rail fired,
manual.yml has a bad entry, ...); 1 = fatal (config unreadable, every upstream
source unreachable, ...) - nothing is written on a fatal error.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = Path(__file__).resolve().parent / "conferences.yml"
DATA_DIR = REPO_ROOT / "deadlines" / "data" / "conferences"
MANUAL_PATH = REPO_ROOT / "deadlines" / "data" / "manual.yml"

CATEGORIES = ["system", "software", "security", "ai"]
TODAY = dt.date.today()
FROM_YEAR = TODAY.year - 2  # same window as deadlines/assets/deadline-tracker.js
TO_YEAR = TODAY.year + 1

CCFDDL_RAW = "https://raw.githubusercontent.com/ccfddl/ccf-deadlines/main/conference/"
SECDL_RAW = ("https://raw.githubusercontent.com/sec-deadlines/"
             "sec-deadlines.github.io/master/_data/conferences.yml")

HEADER = (
    "# AUTO-GENERATED by deadlines/scripts/update_deadlines.py — do not edit by hand.\n"
    "# Human corrections belong in deadlines/data/manual.yml (it overrides this file).\n"
    "# Sources: ccfddl/ccf-deadlines, sec-deadlines.github.io "
    "(mapping: deadlines/scripts/conferences.yml)\n"
)

DEADLINE_RE = re.compile(r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$")
TIMEZONE_RE = re.compile(r"^(AoE|PST|PDT|UTC([+-]\d{1,2})?|[A-Za-z]+(/[A-Za-z0-9_+\-]+)+)$")
# ccfddl timeline entries that are not paper-submission cycles (pre-2024 legacy).
SKIP_COMMENT_RE = re.compile(r"abstract|registration|notification|camera[ -]?ready|workshop", re.I)
FIELD_ORDER = ["title", "year", "id", "full_name", "type", "tier", "link",
               "abstract_deadline", "deadline", "timezone", "place", "date",
               "start", "end", "note"]
SAFETY_RAIL_DAYS = 90
# Fields a manual.yml entry may override; propagated verbatim into generated data.
MANUAL_FIELDS = ("abstract_deadline", "deadline", "timezone", "place", "date",
                 "link", "note", "start", "end")
# Placeholder notes auto-cleared once the record gains a concrete deadline.
STALE_NOTE_RE = re.compile(
    r"not (?:yet |publicly )?(?:available|announced)|announced yet|not yet available", re.I)
CFG_ENFORCE_FROM = TODAY.year  # cfg-owned fields enforced on editions >= this year

warnings: list[str] = []
health: list[str] = []  # degraded-run reasons; non-empty -> exit code 2
actions: list[tuple[str, str]] = []  # (action, description)


def warn(msg: str) -> None:
    warnings.append(msg)


def degrade(msg: str) -> None:
    """A warning that additionally marks the whole run degraded (exit 2)."""
    warnings.append("[!] " + msg)
    health.append(msg)


def as_list(value):
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def clean(value) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


# --------------------------------------------------------------------------- fetch

def http_get(url: str, timeout: int = 30, retries: int = 2) -> str:
    last = None
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "secai-lab-deadline-updater/1.0"})
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return resp.read().decode("utf-8")
        except Exception as exc:  # noqa: BLE001 - any network error is retryable
            last = exc
            if attempt < retries:
                time.sleep(2 * (attempt + 1))
    raise RuntimeError(f"{url}: {last}")


# --------------------------------------------------------------------- conversion

def norm_dt(value):
    """Normalize an upstream deadline value to 'YYYY-MM-DD HH:MM' (or None)."""
    if value is None:
        return None
    if isinstance(value, dt.datetime):
        return value.strftime("%Y-%m-%d %H:%M")
    if isinstance(value, dt.date):
        return None  # date-only values carry no usable time - skip
    s = str(value).strip()
    if not s or s.upper() in ("TBD", "TBA"):
        return None
    m = re.match(r"^(\d{4})-(\d{1,2})-(\d{1,2})[ T](\d{1,2}):(\d{2})(?::\d{2})?$", s)
    if not m:
        return None
    y, mo, d, h, mi = m.groups()
    return f"{int(y):04d}-{int(mo):02d}-{int(d):02d} {int(h):02d}:{mi}"


def none_if_tba(value):
    s = clean(value)
    if not s or s.upper() in ("TBD", "TBA"):
        return None
    return s


def map_ccfddl_tz(value):
    s = clean(value)
    if not s:
        return None
    if s == "AoE":
        return "AoE"
    if s in ("UTC", "UTC+0"):
        return "UTC+0"
    if s == "PT":
        # IANA name, not fixed "PST": the frontend resolves IANA zones
        # DST-correctly, while its PST branch is pinned to -08:00 year-round.
        return "America/Los_Angeles"
    if re.fullmatch(r"UTC[+-]\d{1,2}", s):
        return s
    return None


def map_secdl_tz(value):
    s = clean(value)
    if not s:
        return "AoE"  # documented sec-deadlines convention: absent = AoE
    m = re.fullmatch(r"Etc/GMT([+-])(\d{1,2})", s)
    if m:  # NOTE: Etc/GMT signs are inverted (Etc/GMT+8 == UTC-8)
        return "UTC" + ("-" if m.group(1) == "+" else "+") + m.group(2)
    if s in ("Etc/GMT", "Etc/UTC", "UTC"):
        return "UTC+0"
    return s  # IANA names pass through; the frontend parses them


def convert_ccfddl(doc, key):
    """ccfddl per-conference file -> {year: candidate}.

    A structural surprise raises (counted as a failed fetch by the caller):
    a silently-empty conversion after an upstream format change would freeze
    the data forever behind a green checkmark.
    """
    out = {}
    if not isinstance(doc, list) or not doc or not isinstance(doc[0], dict):
        raise RuntimeError("unexpected file structure")
    if len(doc) > 1:
        warn(f"ccfddl {key}: {len(doc)} records in file, using the first")
    confs = doc[0].get("confs")
    if not isinstance(confs, list):
        raise RuntimeError("unexpected file structure (no confs list)")
    for conf in confs:
        year = conf.get("year")
        if not isinstance(year, int) or not FROM_YEAR <= year <= TO_YEAR:
            continue
        deadlines, abstracts = [], []
        for entry in conf.get("timeline") or []:
            comment = clean(entry.get("comment"))
            # An entry carrying its own abstract_deadline is a real paper cycle
            # no matter what its comment mentions.
            if (SKIP_COMMENT_RE.search(comment)
                    and norm_dt(entry.get("abstract_deadline")) is None):
                warn(f"ccfddl {key} {year}: skipped non-cycle timeline entry ({comment!r})")
                continue
            deadline = norm_dt(entry.get("deadline"))
            if deadline is None:
                continue  # TBD / unparsable cycle
            deadlines.append(deadline)
            abstracts.append(norm_dt(entry.get("abstract_deadline")))
        if not deadlines:
            continue
        link = clean(conf.get("link"))
        out[year] = {
            "deadlines": deadlines,
            "abstracts": abstracts,
            "timezone": map_ccfddl_tz(conf.get("timezone")),
            "place": none_if_tba(conf.get("place")),
            "date": none_if_tba(conf.get("date")),
            "link": link if link.startswith("http") else None,
            "source": "ccfddl",
        }
    return out


def convert_secdl(records, locator, key):
    """sec-deadlines record -> {year: candidate} (latest edition only)."""
    if isinstance(locator, str):
        locator = {"name": locator}
    name, needle = locator.get("name"), clean(locator.get("description_contains"))
    matches = [r for r in records
               if clean(r.get("name")) == name
               and (not needle or needle.lower() in clean(r.get("description")).lower())]
    if not matches:
        degrade(f"secdl {key}: no record named {name!r} - the upstream record was "
                "likely renamed or removed; fix the locator in conferences.yml")
        return {}
    if len(matches) > 1:
        degrade(f"secdl {key}: {len(matches)} ambiguous records named {name!r}, skipped "
                "- add a description_contains filter in conferences.yml")
        return {}
    rec = matches[0]
    year = rec.get("year")
    if not isinstance(year, int) or not FROM_YEAR <= year <= TO_YEAR:
        return {}
    deadlines = []
    for value in as_list(rec.get("deadline")):
        s = str(value).replace("%Y", str(year - 1)).replace("%y", str(year))
        deadline = norm_dt(s)
        if deadline is not None:
            deadlines.append(deadline)
    if not deadlines:
        return {}
    abstracts = [norm_dt(a) for a in as_list(rec.get("abstract_deadline"))]
    abstracts = (abstracts + [None] * len(deadlines))[:len(deadlines)]
    date = none_if_tba(rec.get("date"))
    if date and not re.search(r"\d{4}", date):
        date = f"{date}, {year}"  # sec-deadlines dates usually omit the year
    link = clean(rec.get("link"))
    return {year: {
        "deadlines": deadlines,
        "abstracts": abstracts,
        "timezone": map_secdl_tz(rec.get("timezone")),
        "place": none_if_tba(rec.get("place")),
        "date": date,
        "link": link if link.startswith("http") else None,
        "source": "secdl",
    }}


# ------------------------------------------------------------------ existing data

def split_blocks(text: str):
    """Split a YAML list file into raw per-record text blocks."""
    lines = text.split("\n")
    starts = [i for i, line in enumerate(lines) if line.startswith("- ")]
    blocks = []
    for j, start in enumerate(starts):
        end = starts[j + 1] if j + 1 < len(starts) else len(lines)
        blocks.append("\n".join(lines[start:end]).rstrip())
    return blocks


def match_target(title: str, targets):
    """Same alias-matching rule as matchTarget() in deadline-tracker.js."""
    ht = clean(title).lower()
    if not ht:
        return None
    for target in targets:
        for alias in target.get("aliases") or [target["key"]]:
            a = str(alias).lower()
            if ht == a or ht.startswith(a + " ") or f" {a} " in ht or ht.endswith(" " + a):
                return target
    return None


def load_existing():
    """-> {(year, category): {'path', 'text', 'items'}}; item = {'data','raw',...}."""
    files = {}
    for year in range(FROM_YEAR, TO_YEAR + 1):
        for cat in CATEGORIES:
            path = DATA_DIR / str(year) / f"{cat}.yml"
            entry = {"path": path, "text": None, "items": []}
            files[(year, cat)] = entry
            if not path.exists():
                continue
            text = path.read_text(encoding="utf-8")
            entry["text"] = text
            try:
                data = yaml.safe_load(text)
            except yaml.YAMLError as exc:
                warn(f"{path}: YAML parse error ({exc}); file left untouched")
                entry["broken"] = True
                continue
            data = data if isinstance(data, list) else []
            blocks = split_blocks(text)
            if len(blocks) != len(data):
                warn(f"{path}: {len(data)} records vs {len(blocks)} text blocks; "
                     "byte-level round-trip unavailable, formatting will be regenerated")
                blocks = [None] * len(data)
            for rec, raw in zip(data, blocks):
                if isinstance(rec, dict):
                    entry["items"].append({"data": rec, "raw": raw, "new_data": None})
    return files


# ------------------------------------------------------------------------- merge

def canon_tz(value):
    s = clean(value)
    if s == "AoE":
        return "UTC-12"
    if s in ("UTC", "UTC+0"):
        return "UTC+0"
    return s


def canon_deadline_field(value):
    values = [norm_dt(v) or (str(v) if v is not None else None) for v in as_list(value)]
    while values and values[-1] is None:
        values.pop()
    return tuple(values)


def canon_record(rec):
    """Comparison form: equates scalar/list, 23:59:59/23:59, AoE/UTC-12, null/absent."""
    out = {}
    for key, value in rec.items():
        if value is None or key == "tba":
            continue
        if key in ("deadline", "abstract_deadline"):
            if canon_deadline_field(value):
                out[key] = canon_deadline_field(value)
        elif key == "timezone":
            out[key] = canon_tz(value)
        elif key in ("start", "end"):
            out[key] = str(value)
        else:
            out[key] = value
    return out


MONTH_NAMES = ["january", "february", "march", "april", "may", "june", "july",
               "august", "september", "october", "november", "december"]
DATE_RANGE_RE = re.compile(
    r"^([A-Za-z.]+)\s*(\d{1,2})\s*(?:-\s*([A-Za-z.]+)?\s*(\d{1,2}))?\s*,?\s*(\d{4})\.?$")


def month_num(token):
    t = clean(token).lower().strip(".")
    if len(t) < 3:
        return None
    for i, name in enumerate(MONTH_NAMES, 1):
        if name.startswith(t):
            return i
    return None


def parse_date_range(value):
    """'April 13-16, 2026' / 'March 30 - April 2, 2027' / 'Dec 7, 2026' ->
    (start_date, end_date), or None when the format is not understood."""
    s = clean(value).replace("–", "-").replace("—", "-").replace("−", "-")
    m = DATE_RANGE_RE.match(s)
    if not m:
        return None
    mon1_tok, day1, mon2_tok, day2, year = m.groups()
    mon1 = month_num(mon1_tok)
    mon2 = month_num(mon2_tok) if mon2_tok else mon1
    if mon1 is None or mon2 is None:
        return None
    try:
        start = dt.date(int(year), mon1, int(day1))
        end = dt.date(int(year), mon2, int(day2)) if day2 else start
        if end < start:  # range wraps into the next calendar year
            end = dt.date(int(year) + 1, mon2, int(day2))
    except ValueError:
        return None
    return start, end


def parse_dl_date(value):
    m = re.match(r"^(\d{4})-(\d{1,2})-(\d{1,2})", str(value or ""))
    if not m:
        return None
    try:
        return dt.date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    except ValueError:
        return None


def rail_triggered(existing, cand_deadlines):
    """True if upstream would move a concrete future deadline by > 90 days."""
    if not existing:
        return False
    future = [d for d in (parse_dl_date(v) for v in as_list(existing.get("deadline")))
              if d is not None and d >= TODAY]
    cand = [d for d in (parse_dl_date(v) for v in cand_deadlines) if d is not None]
    if not future or not cand:
        return False
    return any(min(abs((c - d).days) for c in cand) > SAFETY_RAIL_DAYS for d in future)


def norm_kept_deadlines(value):
    """Normalize deadline values kept from an existing record (strip :SS)."""
    if isinstance(value, list):
        return [norm_dt(v) or v for v in value]
    if value is None:
        return None
    return norm_dt(value) or value


def load_manual(targets):
    """manual.yml -> {(canonical key, year): record}.

    The overrides are propagated into the generated files every run so both
    frontend sources agree byte-for-byte - this is what lets a manual entry
    move a deadline in either direction without any frontend merge heuristics
    getting in the way. A malformed entry degrades the run: a hand-typed row
    the frontend would silently drop must never go unnoticed.
    """
    if not MANUAL_PATH.exists():
        return {}
    try:
        records = yaml.safe_load(MANUAL_PATH.read_text(encoding="utf-8")) or []
    except yaml.YAMLError as exc:
        degrade(f"manual.yml: YAML parse error ({exc}); overrides skipped this run")
        return {}
    if not isinstance(records, list):
        degrade("manual.yml: unexpected structure (not a list); overrides skipped")
        return {}
    out = {}
    for rec in records:
        if not isinstance(rec, dict):
            continue
        title, year = rec.get("title"), rec.get("year")
        target = match_target(title, targets)
        if target is None:
            degrade(f"manual.yml: title {title!r} matches no target; "
                    "the frontend silently drops such rows - fix the title")
            continue
        if clean(title) != target["key"]:
            degrade(f"manual.yml: title {title!r} must be the canonical key "
                    f"{target['key']!r} (alias matching differs between the script "
                    "and the frontend; non-canonical titles can merge wrongly)")
            continue
        if not isinstance(year, int):
            degrade(f"manual.yml: {target['key']} entry has no integer year; skipped")
            continue
        if (target["key"], year) in out:
            degrade(f"manual.yml: duplicate entry for {target['key']} {year}; "
                    "using the first")
            continue
        out[(target["key"], year)] = rec
    return out


def enforce_cfg_fields(merged, target, year):
    """conferences.yml owns title-adjacent metadata: enforce id / full_name /
    type / tier on current and future editions so a mapping fix self-corrects
    in the data. Past editions keep their historical values."""
    if year < CFG_ENFORCE_FROM:
        if not merged.get("id"):
            merged["id"] = f"{target['slug']}{year % 100:02d}"
        merged.setdefault("full_name", target["full_name"])
        merged.setdefault("type", target.get("type", "conference"))
        if target.get("tier") and not merged.get("tier"):
            merged["tier"] = target["tier"]
        return
    merged["id"] = f"{target['slug']}{year % 100:02d}"
    merged["full_name"] = target["full_name"]
    merged["type"] = target.get("type", "conference")
    if str(merged.get("tier", "")).upper() in ("TBA", "TBD"):
        merged.pop("tier", None)  # placeholder, not a curated tier
    if target.get("tier"):
        merged["tier"] = target["tier"]


def apply_manual_override(merged, man):
    """Copy every override field manual.yml sets into the generated record;
    a field EXPLICITLY set to null deletes it (for values fabricated
    upstream, e.g. an abstract deadline the official CFP does not have).
    Returns the fields whose value materially changed."""
    changed = []
    for field in MANUAL_FIELDS:
        if field not in man:
            continue
        value = man[field]
        if value is None:
            if canon_record({field: merged.get(field)}):
                changed.append(field)
            merged.pop(field, None)
            continue
        if canon_record({field: merged.get(field)}) != canon_record({field: value}):
            changed.append(field)
        merged[field] = value
    if man.get("date") and not (man.get("start") and man.get("end")):
        parsed = parse_date_range(man["date"])
        if parsed:
            merged["start"], merged["end"] = parsed
    return changed


def manual_matches_upstream(man, cand):
    """True when upstream now agrees with every value manual.yml overrides -
    the entry is obsolete and can be removed."""
    checks = {
        "deadline": lambda: (canon_deadline_field(man.get("deadline"))
                             == canon_deadline_field(cand["deadlines"])),
        "abstract_deadline": lambda: (canon_deadline_field(man.get("abstract_deadline"))
                                      == canon_deadline_field([a for a in cand["abstracts"] if a])),
        "timezone": lambda: canon_tz(man.get("timezone")) == canon_tz(cand.get("timezone")),
        "place": lambda: clean(man.get("place")) == clean(cand.get("place")),
        "date": lambda: clean(man.get("date")) == clean(cand.get("date")),
        "link": lambda: clean(man.get("link")) == clean(cand.get("link")),
    }
    for field, check in checks.items():
        if field in man and not check():
            return False
    return True


def maybe_clear_stale_note(merged, existing, key, year):
    """Placeholder notes ('CFP not announced yet', ...) are cleared the moment
    the record gains its first concrete deadline."""
    note = merged.get("note")
    if not existing or not note:
        return
    had = bool(canon_deadline_field(existing.get("deadline")))
    has = bool(canon_deadline_field(merged.get("deadline")))
    if not had and has and STALE_NOTE_RE.search(str(note)):
        warn(f"{key} {year}: dropped stale placeholder note ({note!r})")
        merged.pop("note", None)


def build_merged(target, year, existing, cand, owned=frozenset()):
    """Apply the merge policy; `owned` names the fields a manual.yml override
    controls - upstream never touches those. Returns (merged_record, railed)."""
    merged = dict(existing) if existing else {}
    merged["title"] = target["key"]
    merged["year"] = year
    railed = "deadline" not in owned and rail_triggered(existing, cand["deadlines"])
    if railed:
        degrade(f"SAFETY RAIL {target['key']} {year}: upstream ({cand['source']}) would move a "
                f"future deadline by > {SAFETY_RAIL_DAYS} days "
                f"({as_list(existing.get('deadline'))} -> {cand['deadlines']}); "
                "existing record kept untouched pending human review")
    else:
        for field in ("link", "place", "date"):
            if cand.get(field) and field not in owned:
                merged[field] = cand[field]
        if (existing and cand.get("date") and "date" not in owned
                and clean(existing.get("date")).upper() not in ("", "TBA")):
            old_range, new_range = parse_date_range(existing["date"]), parse_date_range(cand["date"])
            if old_range and new_range and old_range != new_range:
                warn(f"CONFERENCE DATE CHANGED {target['key']} {year}: "
                     f"{existing['date']!r} -> {cand['date']!r} (source {cand['source']}) "
                     "- verify against the official page; override in manual.yml if upstream is wrong")
        if cand.get("date") and "date" not in owned:
            # Keep start/end consistent with the (upstream-won) date string -
            # and never let stale values sit next to a CHANGED date they may
            # contradict. An unchanged-but-unparsable date keeps its start/end.
            parsed = parse_date_range(cand["date"])
            if parsed:
                merged["start"], merged["end"] = parsed
            elif clean(cand["date"]) != clean((existing or {}).get("date")):
                merged.pop("start", None)
                merged.pop("end", None)
        if "deadline" not in owned:
            merged["deadline"] = (cand["deadlines"][0] if len(cand["deadlines"]) == 1
                                  else list(cand["deadlines"]))
            if any(cand["abstracts"]) and "abstract_deadline" not in owned:
                abstracts = (cand["abstracts"] + [None] * len(cand["deadlines"]))[:len(cand["deadlines"])]
                merged["abstract_deadline"] = abstracts[0] if len(abstracts) == 1 else abstracts
            # else: the existing abstract_deadline (if any) stays untouched
        if ("timezone" not in owned and cand.get("timezone")
                and canon_tz(cand["timezone"]) != canon_tz(merged.get("timezone"))):
            merged["timezone"] = cand["timezone"]
    merged["deadline"] = norm_kept_deadlines(merged.get("deadline"))
    merged["abstract_deadline"] = norm_kept_deadlines(merged.get("abstract_deadline"))
    if merged["abstract_deadline"] is None:
        merged.pop("abstract_deadline")
    merged.pop("tba", None)  # legacy flag: meaningless once a record has real data
    if merged.get("timezone") == "TBA":
        merged.pop("timezone")
    enforce_cfg_fields(merged, target, year)
    return merged, railed


def validate(rec, canonical_keys, require_deadline=True):
    errors = []
    if rec.get("title") not in canonical_keys:
        errors.append(f"title {rec.get('title')!r} is not a canonical key")
    year = rec.get("year")
    if not isinstance(year, int) or not FROM_YEAR <= year <= TO_YEAR:
        errors.append(f"year {year!r} outside {FROM_YEAR}..{TO_YEAR}")
    def is_tba(value):
        return str(value).upper() in ("TBA", "TBD")

    # "TBA" is the established placeholder convention in this dataset (the
    # frontend renders it as a TBA row) - tolerated wherever a concrete
    # deadline is not required.
    concrete = [d for d in as_list(rec.get("deadline")) if d is not None and not is_tba(d)]
    if not concrete and require_deadline:
        errors.append("no concrete deadline")
    errors += [f"bad deadline {d!r}" for d in concrete if not DEADLINE_RE.match(str(d))]
    errors += [f"bad abstract_deadline {a!r}" for a in as_list(rec.get("abstract_deadline"))
               if a is not None and not is_tba(a) and not DEADLINE_RE.match(str(a))]
    tz = rec.get("timezone")
    if tz is not None and not is_tba(tz) and not TIMEZONE_RE.match(str(tz)):
        errors.append(f"bad timezone {tz!r}")
    link = rec.get("link")
    if link is not None and not re.match(r"^https?://", str(link)):
        errors.append(f"bad link {link!r}")
    return errors


# ---------------------------------------------------------------------- emission

def yaml_quote(value) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_scalar(key, value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, (dt.datetime, dt.date)):
        return value.strftime("%Y-%m-%d")
    s = str(value)
    if key in ("id", "link", "timezone", "start", "end", "type"):
        return s
    if key == "tier" and re.fullmatch(r"T\d", s):
        return s
    return yaml_quote(s)


def render_record(rec) -> str:
    keys = [k for k in FIELD_ORDER if k in rec] + [k for k in rec if k not in FIELD_ORDER]
    lines = []
    for key in keys:
        value = rec[key]
        if value is None:
            continue
        prefix = "- " if not lines else "  "
        if key in ("deadline", "abstract_deadline") and isinstance(value, list):
            lines.append(f"{prefix}{key}:")
            lines += ["    - " + ("null" if item is None else yaml_quote(item)) for item in value]
        else:
            lines.append(f"{prefix}{key}: {render_scalar(key, value)}")
    return "\n".join(lines)


def assemble_file(items) -> str:
    blocks = sorted(items, key=lambda it: str(it["sort_title"]))
    return HEADER + "\n" + "\n\n".join(b["text"] for b in blocks) + "\n"


# -------------------------------------------------------------------------- main

def load_config():
    cfg = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    targets = cfg["conferences"]
    default_priority = (cfg.get("defaults") or {}).get("source_priority") or ["secdl", "ccfddl"]
    for target in targets:
        sources = target.get("sources")
        target["manual_only"] = sources == "manual-only"
        target["sources"] = sources if isinstance(sources, dict) else {}
        priority = target.get("source_priority") or default_priority
        target["priority"] = [s for s in priority if s in target["sources"]]
    return targets


def fetch_upstream(targets):
    """-> ({source: {key: {year: candidate}}}, failed, status_lines, any_source_ok).

    `failed` maps source name -> set of target keys whose fetch from that source
    FAILED (network/parse error), as opposed to succeeded-but-has-no-record.
    The merge loop must never fall back past a failed higher-priority source:
    stale lower-priority data would clobber values the failed source owns.
    """
    data = {"ccfddl": {}, "secdl": {}}
    failed = {"ccfddl": set(), "secdl": set()}
    status = []

    ccfddl_targets = [t for t in targets if "ccfddl" in t["sources"]]
    ok = 0
    for target in ccfddl_targets:
        path = target["sources"]["ccfddl"]
        url = CCFDDL_RAW + urllib.parse.quote(path)
        try:
            doc = yaml.safe_load(http_get(url))
            data["ccfddl"][target["key"]] = convert_ccfddl(doc, target["key"])
            ok += 1
        except Exception as exc:  # noqa: BLE001
            failed["ccfddl"].add(target["key"])
            degrade(f"ccfddl fetch failed for {target['key']} ({path}): {exc}")
    status.append(f"ccfddl: {ok}/{len(ccfddl_targets)} conference files fetched")
    ccfddl_ok = ok > 0

    secdl_ok = False
    try:
        records = yaml.safe_load(http_get(SECDL_RAW))
        if not isinstance(records, list):
            raise RuntimeError("unexpected structure (not a list)")
        for target in targets:
            if "secdl" in target["sources"]:
                data["secdl"][target["key"]] = convert_secdl(
                    records, target["sources"]["secdl"], target["key"])
        status.append(f"secdl: ok ({len(records)} records)")
        secdl_ok = True
    except Exception as exc:  # noqa: BLE001
        failed["secdl"] = {t["key"] for t in targets if "secdl" in t["sources"]}
        degrade(f"secdl fetch failed: {exc}")
        status.append("secdl: FAILED")

    return data, failed, status, (ccfddl_ok or secdl_ok)


def sources_disagree(a, b):
    """True if two candidates for the same edition differ materially (> 1 day on
    any cycle, or a different cycle count). 1-day tolerance absorbs equivalent
    instants encoded in different timezones (e.g. AoE vs UTC)."""
    da = sorted(d for d in (parse_dl_date(v) for v in a["deadlines"]) if d)
    db = sorted(d for d in (parse_dl_date(v) for v in b["deadlines"]) if d)
    if len(da) != len(db):
        return True
    return any(abs((x - y).days) > 1 for x, y in zip(da, db))


def cross_fill_abstracts(winner, others):
    """Adopt the losing source's abstract deadlines when cycles line up exactly."""
    if any(winner["abstracts"]):
        return
    for other in others:
        if (len(other["deadlines"]) == len(winner["deadlines"]) and any(other["abstracts"])
                and all(o[:10] == w[:10] for o, w in zip(other["deadlines"], winner["deadlines"]))):
            winner["abstracts"] = list(other["abstracts"])
            return


def describe_changes(old, new):
    changes = []
    for key in sorted(set(old) | set(new)):
        if old.get(key) != new.get(key):
            changes.append(f"{key}: {old.get(key)!r} -> {new.get(key)!r}")
    return changes


def main() -> int:
    # Data and summaries contain non-ASCII (venue names); never let a legacy
    # console encoding (e.g. cp949) crash the run.
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dry-run", action="store_true",
                        help="print the would-be changes without writing files")
    parser.add_argument("--watchlist", metavar="FILE",
                        help="also write a JSON audit watchlist of records worth "
                             "verifying against official sources (written even "
                             "with --dry-run; it is an audit artifact, not data)")
    args = parser.parse_args()

    try:
        targets = load_config()
    except Exception as exc:  # noqa: BLE001
        print(f"FATAL: cannot load {CONFIG_PATH}: {exc}")
        return 1
    canonical_keys = {t["key"] for t in targets}
    by_key = {t["key"]: t for t in targets}

    upstream, failed_fetches, fetch_status, any_ok = fetch_upstream(targets)
    if not any_ok:
        print("\n".join(fetch_status))
        print("FATAL: every upstream source failed; nothing written.")
        return 1

    files = load_existing()
    manual = load_manual(targets)

    # Index existing records by (canonical key, edition year) and re-file any
    # record sitting in the wrong year/category bucket (conferences.yml owns
    # the category; the record's own year field owns the year).
    index = {}
    for (year, cat), entry in files.items():
        for item in entry["items"]:
            rec = item["data"]
            target = match_target(rec.get("title") or rec.get("name"), targets)
            rec_year = rec.get("year") if isinstance(rec.get("year"), int) else year
            item["bucket"] = (year, cat)
            item["target_key"] = target["key"] if target else None
            if target:
                home = (rec_year, target["category"])
                if home != (year, cat):
                    if home in files and not files[home].get("broken"):
                        warn(f"{target['key']} {rec_year}: re-filed from "
                             f"{year}/{cat}.yml into {home[0]}/{home[1]}.yml")
                        item["bucket"] = home
                    else:
                        warn(f"{target['key']} {rec_year}: belongs in "
                             f"{rec_year}/{target['category']}.yml but that file is "
                             "unavailable; left in place")
                if (target["key"], rec_year) in index:
                    degrade(f"duplicate record for {target['key']} {rec_year} in repo data; "
                            "only the first copy is auto-updated")
                else:
                    index[(target["key"], rec_year)] = item

    # Merge upstream candidates into existing records / create new ones.
    new_items = []
    kept, updated, created = [], [], []
    candidate_done = set()
    disagreements = set()
    for target in targets:
        # Never fall back past a source whose FETCH failed (vs. has no record):
        # its stale lower-priority sibling must not clobber data it owns.
        usable = []
        for src in target["priority"]:
            if target["key"] in failed_fetches.get(src, set()):
                if usable or len(target["priority"]) > 1:
                    warn(f"{target['key']}: source '{src}' unavailable this run; "
                         "not falling back to lower-priority sources (existing data kept)")
                break
            usable.append(src)
        per_source = {src: upstream.get(src, {}).get(target["key"], {}) for src in usable}
        years = sorted({y for cands in per_source.values() for y in cands})
        for year in years:
            ordered = [per_source[src][year] for src in usable if year in per_source[src]]
            winner = dict(ordered[0])
            for other in ordered[1:]:
                if sources_disagree(winner, other):
                    disagreements.add((target["key"], year))
                    warn(f"CROSS-SOURCE DISAGREEMENT {target['key']} {year}: "
                         f"{winner['source']}={winner['deadlines']} vs "
                         f"{other['source']}={other['deadlines']}; using {winner['source']} "
                         "- verify against the official CFP")
            cross_fill_abstracts(winner, ordered[1:])
            item = index.get((target["key"], year))
            existing = item["data"] if item else None
            man = manual.get((target["key"], year))
            owned = frozenset(f for f in MANUAL_FIELDS if man and f in man)
            merged, railed = build_merged(target, year, existing, winner, owned)
            if man is None or man.get("note") is None:
                maybe_clear_stale_note(merged, existing, target["key"], year)
            if man is not None:
                if manual_matches_upstream(man, winner):
                    warn(f"manual.yml override for {target['key']} {year} matches "
                         "upstream now; the entry can be removed")
                changed_fields = apply_manual_override(merged, man)
                if changed_fields:
                    warn(f"manual override applied for {target['key']} {year}: "
                         + ", ".join(changed_fields))
            errors = validate(merged, canonical_keys)
            if errors:
                degrade(f"validation failed for {target['key']} {year} "
                        f"({'; '.join(errors)}); kept existing entry" if existing
                        else f"validation failed for new {target['key']} {year} "
                             f"({'; '.join(errors)}); record dropped")
                continue
            candidate_done.add((target["key"], year))
            if existing is not None:
                if canon_record(merged) == canon_record(existing):
                    kept.append(f"{target['key']} {year}")
                else:
                    item["new_data"] = merged
                    changes = describe_changes(canon_record(existing), canon_record(merged))
                    label = " [RAILED]" if railed else ""
                    updated.append(f"{target['key']} {year} ({winner['source']}){label}: "
                                   + "; ".join(changes))
            else:
                created.append(f"{target['key']} {year} ({winner['source']}) -> "
                               f"{year}/{target['category']}.yml")
                new_items.append({"bucket": (year, target["category"]),
                                  "record": merged, "sort_title": merged["title"]})

    # Records with no upstream candidate this run still get cfg-field
    # normalization and manual overrides applied (they would otherwise
    # round-trip byte-for-byte and never self-correct).
    for (key, year), item in sorted(index.items()):
        if item["new_data"] is not None or (key, year) in candidate_done:
            continue
        target = by_key[key]
        existing = item["data"]
        merged = dict(existing)
        merged["title"] = key
        merged["year"] = year
        merged["deadline"] = norm_kept_deadlines(merged.get("deadline"))
        merged["abstract_deadline"] = norm_kept_deadlines(merged.get("abstract_deadline"))
        if merged["abstract_deadline"] is None:
            merged.pop("abstract_deadline")
        enforce_cfg_fields(merged, target, year)
        man = manual.get((key, year))
        if man is not None:
            changed_fields = apply_manual_override(merged, man)
            if changed_fields:
                warn(f"manual override applied for {key} {year}: "
                     + ", ".join(changed_fields))
            if man.get("note") is None:
                maybe_clear_stale_note(merged, existing, key, year)
        if canon_record(merged) == canon_record(existing):
            continue
        errors = validate(merged, canonical_keys, require_deadline=False)
        if errors:
            degrade(f"validation failed for normalized {key} {year} "
                    f"({'; '.join(errors)}); kept existing entry")
            continue
        item["new_data"] = merged
        updated.append(f"{key} {year} (normalized/manual): "
                       + "; ".join(describe_changes(canon_record(existing),
                                                    canon_record(merged))))

    # Existing matched records with no upstream candidate are implicitly kept.
    for (key, year), item in sorted(index.items()):
        if item["new_data"] is None and f"{key} {year}" not in kept:
            has_candidate = any(year in upstream.get(src, {}).get(key, {})
                                for src in ("ccfddl", "secdl"))
            if not has_candidate:
                kept.append(f"{key} {year} (no upstream)")

    # Coverage: every target should have some record for the upcoming cycle
    # year, or it silently never appears on the page (manual-only venues are
    # exactly the ones nobody notices going missing).
    next_year = TODAY.year + 1
    covered = {key for (key, year) in index if year >= next_year}
    covered |= {it["record"]["title"] for it in new_items
                if it["record"]["year"] >= next_year}
    gap_targets = []
    for target in targets:
        if target["key"] not in covered:
            gap_targets.append(target["key"])
            hint = ("manual-only source; add it to deadlines/data/manual.yml "
                    "or the data files by hand"
                    if target.get("manual_only") else "no upstream edition yet")
            warn(f"coverage gap: {target['key']} has no {next_year} entry ({hint})")

    # Audit watchlist: the small subset of records a verification pass (human
    # or agent) should check against OFFICIAL conference pages this week.
    if args.watchlist:
        horizon = TODAY + dt.timedelta(days=45)
        watchlist = []
        final_records = [(key, year, item["new_data"] or item["data"])
                         for (key, year), item in sorted(index.items())]
        final_records += [(it["record"]["title"], it["record"]["year"], it["record"])
                          for it in new_items]
        for key, year, rec in final_records:
            concrete = [d for d in (parse_dl_date(v) for v in as_list(rec.get("deadline")))
                        if d is not None]
            # Past editions with concrete, passed deadlines are frozen history:
            # only future-relevant records earn weekly verification effort.
            relevant = not concrete or any(d >= TODAY for d in concrete)
            reasons = []
            if year >= TODAY.year and not concrete:
                reasons.append("tba-upcoming-cycle")
            if any(TODAY <= d <= horizon for d in concrete):
                reasons.append("deadline-within-45-days")
            if relevant and (key, year) in disagreements:
                reasons.append("cross-source-disagreement")
            if year >= TODAY.year and rec.get("note") and STALE_NOTE_RE.search(str(rec["note"])):
                reasons.append("stale-placeholder-note")
            if relevant and (key, year) in manual:
                reasons.append("manual-override-active")
            if reasons:
                watchlist.append({
                    "title": key, "year": year,
                    "category": by_key[key]["category"],
                    "file": f"deadlines/data/conferences/{year}/{by_key[key]['category']}.yml",
                    "reasons": reasons,
                    "record": {f: (str(rec[f]) if isinstance(rec.get(f), (dt.date, dt.datetime))
                                   else rec.get(f))
                               for f in ("deadline", "abstract_deadline", "timezone",
                                         "place", "date", "link", "note")
                               if rec.get(f) is not None},
                })
        for key in gap_targets:
            watchlist.append({"title": key, "year": next_year,
                              "category": by_key[key]["category"], "file": None,
                              "reasons": ["coverage-gap"], "record": {}})
        Path(args.watchlist).write_text(
            json.dumps(watchlist, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    # Assemble output files (records land in their computed bucket, so a
    # re-filed record moves between files atomically in the same run).
    bucket_items = {}
    for entry in files.values():
        for item in entry["items"]:
            bucket_items.setdefault(item["bucket"], []).append(item)
    results = []  # (path, old_text, new_text)
    for (year, cat), entry in sorted(files.items()):
        if entry.get("broken"):
            continue
        blocks = []
        for item in bucket_items.get((year, cat), []):
            rec = item["new_data"] or item["data"]
            if item["new_data"] is not None or item["raw"] is None:
                text = render_record(rec)
            else:
                text = item["raw"]  # byte-level round-trip for untouched records
            blocks.append({"text": text, "sort_title": rec.get("title") or ""})
        for item in new_items:
            if item["bucket"] == (year, cat):
                blocks.append({"text": render_record(item["record"]),
                               "sort_title": item["sort_title"]})
        if not blocks:
            if entry["text"] is not None:
                # Every record moved elsewhere: leave a valid empty list so
                # the frontend fetch still parses.
                new_text = HEADER + "\n[]\n"
                if new_text != entry["text"]:
                    results.append((entry["path"], entry["text"], new_text))
            continue  # never create empty files
        new_text = assemble_file(blocks)
        if new_text != entry["text"]:
            results.append((entry["path"], entry["text"], new_text))

    # ------------------------------------------------------------------ summary
    print("== Fetch status ==")
    print("\n".join(fetch_status))
    print(f"\n== Actions ({FROM_YEAR}..{TO_YEAR}) ==")
    for line in created:
        print(f"  new      {line}")
    for line in updated:
        print(f"  updated  {line}")
    print(f"  kept     {len(kept)}: {', '.join(sorted(kept))}")
    if warnings:
        print("\n== Warnings ==")
        for line in warnings:
            print(f"  {line}")
    print("\n== Files ==")
    if not results:
        print("  no file changes")
    for path, old_text, new_text in results:
        rel = path.relative_to(REPO_ROOT)
        state = "create" if old_text is None else "update"
        if args.dry_run:
            print(f"  would {state} {rel} ({len(new_text.splitlines())} lines)")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            tmp = path.with_name(path.name + ".tmp")
            tmp.write_text(new_text, encoding="utf-8")
            os.replace(tmp, path)  # atomic: a crash mid-write can't truncate live data
            print(f"  {state}d {rel} ({len(new_text.splitlines())} lines)")
    if args.watchlist:
        print(f"\n== Watchlist ==\n  {len(watchlist)} record(s) -> {args.watchlist}")
    if health:
        print(f"\nHEALTH: DEGRADED - {len(health)} issue(s) marked [!] above "
              "need human attention (exit 2)")
    else:
        print("\nHEALTH: ok")
    if args.dry_run:
        print("\n(dry run: nothing was written)")
    return 2 if health else 0


if __name__ == "__main__":
    sys.exit(main())
