#!/usr/bin/env python3
"""Regenerate deadlines/data/conferences/<year>/<category>.yml from upstream trackers.

Sources (see deadlines/scripts/conferences.yml for the per-venue mapping):
  * ccfddl/ccf-deadlines  - one YAML file per conference on GitHub (multi-year history)
  * sec-deadlines.github.io - single _data/conferences.yml (latest edition only)

Merge policy (per target venue and edition year):
  * no upstream record            -> the existing repo entry is kept (byte-for-byte
    unless the normalization rules below change it)
  * upstream record exists        -> upstream wins for deadline / abstract_deadline /
    timezone / place / date / link (only where upstream has a real, non-TBA value);
    start / end are re-derived from the winning date string when it parses, and
    dropped when it does not, so they never contradict it
  * manual.yml overrides beat upstream on every field they set, in either
    direction, and are propagated into the generated files on every run so the
    frontend's two sources always agree; manual.yml itself is never written
  * conferences.yml owns title / id / full_name / type / tier: they are enforced
    on current and future editions (past editions keep their historical values)
  * records are re-filed into the year/category bucket conferences.yml assigns
  * a placeholder note ("CFP not announced yet", ...) is cleared automatically
    the moment the record gains its first concrete deadline
  * existing entries are never deleted
  * safety rail: an existing concrete FUTURE deadline is never moved by more than
    90 days by upstream data - such records are kept untouched, marked degraded,
    and retained for the weekly official-source audit

Usage:
  python3 deadlines/scripts/update_deadlines.py            # update files in place
  python3 deadlines/scripts/update_deadlines.py --dry-run  # print changes only

Exit codes: 0 = healthy (with or without changes); 2 = degraded - files were
still written where safe, but the pipeline must retry or escalate an
infrastructure fault (a source fetch failed or changed shape, validation
rejected a record, the safety rail fired, manual.yml has a bad entry, ...);
1 = fatal (config unreadable, every upstream source unreachable, ...) - nothing
is written on a fatal error.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request
import zoneinfo
from pathlib import Path

import yaml

import audit_state as AS

# An IANA-shaped timezone the frontend cannot resolve does not fail loudly -
# parseZoneDeadline() falls through to its -12:00 branch and renders the
# deadline as AoE, i.e. LATER than the truth. Only validate zone names when a
# tz database is actually present (Windows needs the `tzdata` package); with
# no database every name would look invalid and the check would be noise.
try:
    zoneinfo.ZoneInfo("America/Los_Angeles")
    TZDB_AVAILABLE = True
except Exception:  # noqa: BLE001 - any failure means "cannot check"
    TZDB_AVAILABLE = False

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = Path(__file__).resolve().parent / "conferences.yml"
DATA_DIR = REPO_ROOT / "deadlines" / "data" / "conferences"
MANUAL_PATH = REPO_ROOT / "deadlines" / "data" / "manual.yml"

CATEGORIES = ["system", "software", "security", "ai"]
TODAY = dt.date.today()
FROM_YEAR = TODAY.year - 2  # same window as deadlines/assets/deadline-tracker.js
TO_YEAR = TODAY.year + 1

CCFDDL_RAW = "https://raw.githubusercontent.com/ccfddl/ccf-deadlines/main/conference/"
SECDL_RAW = ("https://raw.githubusercontent.com/sec-deadlines/"
             "sec-deadlines.github.io/master/_data/conferences.yml")

HEADER = (
    "# AUTO-GENERATED by deadlines/scripts/update_deadlines.py — pipeline-owned.\n"
    "# Verified audit corrections persist in deadlines/data/manual.yml.\n"
    "# Sources: ccfddl/ccf-deadlines, sec-deadlines.github.io "
    "(mapping: deadlines/scripts/conferences.yml)\n"
)

DEADLINE_RE = re.compile(r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$")
TIMEZONE_RE = re.compile(r"^(AoE|PST|PDT|UTC([+-]\d{1,2})?|[A-Za-z]+(/[A-Za-z0-9_+\-]+)+)$")
# ccfddl timeline entries that are not paper-submission cycles (pre-2024 legacy).
SKIP_COMMENT_RE = re.compile(r"abstract|registration|notification|camera[ -]?ready|workshop", re.I)
FIELD_ORDER = ["title", "year", "id", "full_name", "type", "tier", "link",
               "abstract_deadline", "deadline", "timezone", "place", "date",
               "start", "end", "note"]
SAFETY_RAIL_DAYS = 90
# Fields a manual.yml entry may override; propagated verbatim into generated data.
MANUAL_FIELDS = ("abstract_deadline", "deadline", "timezone", "place", "date",
                 "link", "note", "start", "end")
# Placeholder notes auto-cleared once the record gains a concrete deadline.
STALE_NOTE_RE = re.compile(
    r"not (?:yet |publicly )?(?:available|announced)|announced yet|not yet available", re.I)
CFG_ENFORCE_FROM = TODAY.year  # cfg-owned fields enforced on editions >= this year

warnings: list[str] = []
health: list[str] = []  # degraded-run reasons; non-empty -> exit code 2
actions: list[tuple[str, str]] = []  # (action, description)


def warn(msg: str) -> None:
    warnings.append(msg)


def degrade(msg: str) -> None:
    """A warning that additionally marks the whole run degraded (exit 2)."""
    warnings.append("[!] " + msg)
    health.append(msg)


def as_list(value):
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def clean(value) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()


# --------------------------------------------------------------------------- fetch

def http_get(url: str, timeout: int = 30, retries: int = 2) -> str:
    last = None
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": "secai-lab-deadline-updater/1.0"})
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return resp.read().decode("utf-8")
        except Exception as exc:  # noqa: BLE001 - any network error is retryable
            last = exc
            if attempt < retries:
                time.sleep(2 * (attempt + 1))
    raise RuntimeError(f"{url}: {last}")


# --------------------------------------------------------------------- conversion

def norm_dt(value):
    """Normalize an upstream deadline value to 'YYYY-MM-DD HH:MM' (or None)."""
    if value is None:
        return None
    if isinstance(value, dt.datetime):
        return value.strftime("%Y-%m-%d %H:%M")
    if isinstance(value, dt.date):
        return None  # date-only values carry no usable time - skip
    s = str(value).strip()
    if not s or s.upper() in ("TBD", "TBA"):
        return None
    m = re.match(r"^(\d{4})-(\d{1,2})-(\d{1,2})[ T](\d{1,2}):(\d{2})(?::\d{2})?$", s)
    if not m:
        return None
    y, mo, d, h, mi = map(int, m.groups())
    try:
        parsed = dt.datetime(y, mo, d, h, mi)
    except ValueError:
        return None
    return parsed.strftime("%Y-%m-%d %H:%M")


def valid_deadline(value) -> bool:
    """Whether *value* is a real, minute-precision repository timestamp."""
    if not isinstance(value, str) or DEADLINE_RE.fullmatch(value) is None:
        return False
    try:
        parsed = dt.datetime.strptime(value, "%Y-%m-%d %H:%M")
    except ValueError:
        return False
    return parsed.strftime("%Y-%m-%d %H:%M") == value


def upstream_dt(value, where: str):
    """Normalize one upstream instant, distinguishing TBA from corruption."""
    if value is None or clean(value).upper() in ("", "TBA", "TBD"):
        return None
    normalized = norm_dt(value)
    if normalized is None:
        raise RuntimeError(f"{where}: invalid deadline value {value!r}")
    return normalized


def valid_fixed_utc_offset(value) -> bool:
    """Validate the integer UTC offsets supported by the frontend.

    Civil time zones range from UTC-12 through UTC+14.  Letting values such as
    UTC+99 through would produce an invalid Luxon DateTime in the browser.
    """
    match = re.fullmatch(r"UTC(?:([+-])(\d{1,2}))?", clean(value))
    if not match:
        return False
    if not match.group(1):
        return True
    offset = int(match.group(2)) * (1 if match.group(1) == "+" else -1)
    return -12 <= offset <= 14


def none_if_tba(value):
    s = clean(value)
    if not s or s.upper() in ("TBD", "TBA"):
        return None
    return s


def map_ccfddl_tz(value):
    s = clean(value)
    if not s:
        return None
    if s == "AoE":
        return "AoE"
    if s in ("UTC", "UTC+0"):
        return "UTC+0"
    if s == "PT":
        # IANA name, not fixed "PST": the frontend resolves IANA zones
        # DST-correctly, while its PST branch is pinned to -08:00 year-round.
        return "America/Los_Angeles"
    if re.fullmatch(r"UTC[+-]\d{1,2}", s) and valid_fixed_utc_offset(s):
        return s
    if TIMEZONE_RE.fullmatch(s) and tz_resolvable(s):
        return s
    raise RuntimeError(f"unsupported or invalid ccfddl timezone {s!r}")


def map_secdl_tz(value):
    s = clean(value)
    if not s:
        return "AoE"  # documented sec-deadlines convention: absent = AoE
    m = re.fullmatch(r"Etc/GMT([+-])(\d{1,2})", s)
    if m:  # NOTE: Etc/GMT signs are inverted (Etc/GMT+8 == UTC-8)
        return "UTC" + ("-" if m.group(1) == "+" else "+") + m.group(2)
    if s in ("Etc/GMT", "Etc/UTC", "UTC"):
        return "UTC+0"
    return s  # IANA names pass through; the frontend parses them


def convert_ccfddl(doc, key):
    """ccfddl per-conference file -> {year: candidate}.

    A structural surprise raises (counted as a failed fetch by the caller):
    a silently-empty conversion after an upstream format change would freeze
    the data forever behind a green checkmark.
    """
    out = {}
    if not isinstance(doc, list) or not doc or not isinstance(doc[0], dict):
        raise RuntimeError("unexpected file structure")
    if len(doc) > 1:
        warn(f"ccfddl {key}: {len(doc)} records in file, using the first")
    confs = doc[0].get("confs")
    if not isinstance(confs, list):
        raise RuntimeError("unexpected file structure (no confs list)")
    for conf in confs:
        year = conf.get("year")
        if not isinstance(year, int) or not FROM_YEAR <= year <= TO_YEAR:
            continue
        deadlines, abstracts = [], []
        for entry in conf.get("timeline") or []:
            comment = clean(entry.get("comment"))
            abstract = upstream_dt(
                entry.get("abstract_deadline"),
                f"ccfddl {key} {year} abstract_deadline",
            )
            # An entry carrying its own abstract_deadline is a real paper cycle
            # no matter what its comment mentions.
            if SKIP_COMMENT_RE.search(comment) and abstract is None:
                warn(f"ccfddl {key} {year}: skipped non-cycle timeline entry ({comment!r})")
                continue
            deadline = upstream_dt(
                entry.get("deadline"), f"ccfddl {key} {year} deadline"
            )
            if deadline is None:
                continue  # explicit TBD/TBA cycle
            deadlines.append(deadline)
            abstracts.append(abstract)
        if not deadlines:
            continue
        link = clean(conf.get("link"))
        out[year] = {
            "deadlines": deadlines,
            "abstracts": abstracts,
            "timezone": map_ccfddl_tz(conf.get("timezone")),
            "place": none_if_tba(conf.get("place")),
            "date": none_if_tba(conf.get("date")),
            "link": link if link.startswith("http") else None,
            "source": "ccfddl",
        }
    return out


def convert_secdl(records, locator, key):
    """sec-deadlines record -> {year: candidate} (latest edition only)."""
    if isinstance(locator, str):
        locator = {"name": locator}
    name, needle = locator.get("name"), clean(locator.get("description_contains"))
    matches = [r for r in records
               if clean(r.get("name")) == name
               and (not needle or needle.lower() in clean(r.get("description")).lower())]
    if not matches:
        raise RuntimeError(
            f"no record named {name!r}; the upstream record may have been renamed"
        )
    if len(matches) > 1:
        raise RuntimeError(f"{len(matches)} ambiguous records named {name!r}")
    rec = matches[0]
    year = rec.get("year")
    if not isinstance(year, int) or not FROM_YEAR <= year <= TO_YEAR:
        return {}
    deadlines = []
    for value in as_list(rec.get("deadline")):
        s = str(value).replace("%Y", str(year - 1)).replace("%y", str(year))
        deadline = upstream_dt(s, f"secdl {key} {year} deadline")
        if deadline is not None:
            deadlines.append(deadline)
    if not deadlines:
        return {}
    abstracts = [upstream_dt(a, f"secdl {key} {year} abstract_deadline")
                 for a in as_list(rec.get("abstract_deadline"))]
    abstracts = (abstracts + [None] * len(deadlines))[:len(deadlines)]
    date = none_if_tba(rec.get("date"))
    if date and not re.search(r"\d{4}", date):
        date = f"{date}, {year}"  # sec-deadlines dates usually omit the year
    link = clean(rec.get("link"))
    return {year: {
        "deadlines": deadlines,
        "abstracts": abstracts,
        "timezone": map_secdl_tz(rec.get("timezone")),
        "place": none_if_tba(rec.get("place")),
        "date": date,
        "link": link if link.startswith("http") else None,
        "source": "secdl",
    }}


# ------------------------------------------------------------------ existing data

def split_blocks(text: str):
    """Split a YAML list file into raw per-record text blocks."""
    lines = text.split("\n")
    starts = [i for i, line in enumerate(lines) if line.startswith("- ")]
    blocks = []
    for j, start in enumerate(starts):
        end = starts[j + 1] if j + 1 < len(starts) else len(lines)
        blocks.append("\n".join(lines[start:end]).rstrip())
    return blocks


def match_target(title: str, targets):
    """Same alias-matching rule as matchTarget() in deadline-tracker.js."""
    ht = clean(title).lower()
    if not ht:
        return None
    for target in targets:
        for alias in target.get("aliases") or [target["key"]]:
            a = str(alias).lower()
            if ht == a or ht.startswith(a + " ") or f" {a} " in ht or ht.endswith(" " + a):
                return target
    return None


def load_existing():
    """-> {(year, category): {'path', 'text', 'items'}}; item = {'data','raw',...}."""
    files = {}
    for year in range(FROM_YEAR, TO_YEAR + 1):
        for cat in CATEGORIES:
            path = DATA_DIR / str(year) / f"{cat}.yml"
            entry = {"path": path, "text": None, "items": []}
            files[(year, cat)] = entry
            if not path.exists():
                continue
            text = path.read_text(encoding="utf-8")
            entry["text"] = text
            try:
                data = yaml.safe_load(text)
            except yaml.YAMLError as exc:
                warn(f"{path}: YAML parse error ({exc}); file left untouched")
                entry["broken"] = True
                continue
            data = data if isinstance(data, list) else []
            blocks = split_blocks(text)
            if len(blocks) != len(data):
                warn(f"{path}: {len(data)} records vs {len(blocks)} text blocks; "
                     "byte-level round-trip unavailable, formatting will be regenerated")
                blocks = [None] * len(data)
            for rec, raw in zip(data, blocks):
                if isinstance(rec, dict):
                    entry["items"].append({"data": rec, "raw": raw, "new_data": None})
    return files


# ------------------------------------------------------------------------- merge

def canon_tz(value):
    s = clean(value)
    if s == "AoE":
        return "UTC-12"
    if s in ("UTC", "UTC+0"):
        return "UTC+0"
    return s


def tz_resolvable(value):
    """False only for an IANA-shaped name no tz database knows.

    AoE / PST / PDT / UTC+-N are handled by the frontend's own branches, so
    they need no lookup. A slash-form name that does not resolve is the
    dangerous case: it passes TIMEZONE_RE, then silently renders as AoE.
    """
    s = clean(value)
    if s.startswith("UTC") and not valid_fixed_utc_offset(s):
        return False
    if "/" not in s or not TZDB_AVAILABLE:
        return True
    try:
        zoneinfo.ZoneInfo(s)
        return True
    except Exception:  # noqa: BLE001 - ZoneInfoNotFoundError and friends
        return False


def canon_deadline_field(value):
    values = [norm_dt(v) or (str(v) if v is not None else None) for v in as_list(value)]
    while values and values[-1] is None:
        values.pop()
    return tuple(values)


def canon_record(rec):
    """Comparison form: equates scalar/list, 23:59:59/23:59, AoE/UTC-12, null/absent."""
    out = {}
    for key, value in rec.items():
        if value is None or key == "tba":
            continue
        if key in ("deadline", "abstract_deadline"):
            if canon_deadline_field(value):
                out[key] = canon_deadline_field(value)
        elif key == "timezone":
            out[key] = canon_tz(value)
        elif key in ("start", "end"):
            out[key] = str(value)
        else:
            out[key] = value
    return out


MONTH_NAMES = ["january", "february", "march", "april", "may", "june", "july",
               "august", "september", "october", "november", "december"]
DATE_RANGE_RE = re.compile(
    r"^([A-Za-z.]+)\s*(\d{1,2})\s*(?:-\s*([A-Za-z.]+)?\s*(\d{1,2}))?\s*,?\s*(\d{4})\.?$")


def month_num(token):
    t = clean(token).lower().strip(".")
    if len(t) < 3:
        return None
    for i, name in enumerate(MONTH_NAMES, 1):
        if name.startswith(t):
            return i
    return None


def parse_date_range(value):
    """'April 13-16, 2026' / 'March 30 - April 2, 2027' / 'Dec 7, 2026' ->
    (start_date, end_date), or None when the format is not understood."""
    s = clean(value).replace("–", "-").replace("—", "-").replace("−", "-")
    m = DATE_RANGE_RE.match(s)
    if not m:
        return None
    mon1_tok, day1, mon2_tok, day2, year = m.groups()
    mon1 = month_num(mon1_tok)
    mon2 = month_num(mon2_tok) if mon2_tok else mon1
    if mon1 is None or mon2 is None:
        return None
    try:
        start = dt.date(int(year), mon1, int(day1))
        end = dt.date(int(year), mon2, int(day2)) if day2 else start
        if end < start:  # range wraps into the next calendar year
            end = dt.date(int(year) + 1, mon2, int(day2))
    except ValueError:
        return None
    return start, end


def parse_dl_date(value):
    m = re.match(r"^(\d{4})-(\d{1,2})-(\d{1,2})", str(value or ""))
    if not m:
        return None
    try:
        return dt.date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    except ValueError:
        return None


def rail_triggered(existing, cand_deadlines):
    """True if upstream would move a concrete future deadline by > 90 days."""
    if not existing:
        return False
    future = [d for d in (parse_dl_date(v) for v in as_list(existing.get("deadline")))
              if d is not None and d >= TODAY]
    cand = [d for d in (parse_dl_date(v) for v in cand_deadlines) if d is not None]
    if not future or not cand:
        return False
    return any(min(abs((c - d).days) for c in cand) > SAFETY_RAIL_DAYS for d in future)


def norm_kept_deadlines(value):
    """Normalize deadline values kept from an existing record (strip :SS)."""
    if isinstance(value, list):
        return [norm_dt(v) or v for v in value]
    if value is None:
        return None
    return norm_dt(value) or value


def load_manual(targets):
    """manual.yml -> {(canonical key, year): record}.

    The overrides are propagated into the generated files every run so both
    frontend sources agree byte-for-byte - this is what lets a manual entry
    move a deadline in either direction without any frontend merge heuristics
    getting in the way. A malformed entry degrades the run: a hand-typed row
    the frontend would silently drop must never go unnoticed.
    """
    if not MANUAL_PATH.exists():
        return {}
    try:
        records = yaml.safe_load(MANUAL_PATH.read_text(encoding="utf-8")) or []
    except yaml.YAMLError as exc:
        degrade(f"manual.yml: YAML parse error ({exc}); overrides skipped this run")
        return {}
    if not isinstance(records, list):
        degrade("manual.yml: unexpected structure (not a list); overrides skipped")
        return {}
    out = {}
    for rec in records:
        if not isinstance(rec, dict):
            continue
        title, year = rec.get("title"), rec.get("year")
        target = match_target(title, targets)
        if target is None:
            degrade(f"manual.yml: title {title!r} matches no target; "
                    "the frontend silently drops such rows - fix the title")
            continue
        if clean(title) != target["key"]:
            degrade(f"manual.yml: title {title!r} must be the canonical key "
                    f"{target['key']!r} (alias matching differs between the script "
                    "and the frontend; non-canonical titles can merge wrongly)")
            continue
        if not isinstance(year, int):
            degrade(f"manual.yml: {target['key']} entry has no integer year; skipped")
            continue
        if (target["key"], year) in out:
            degrade(f"manual.yml: duplicate entry for {target['key']} {year}; "
                    "using the first")
            continue
        out[(target["key"], year)] = rec
    return out


def enforce_cfg_fields(merged, target, year):
    """conferences.yml owns title-adjacent metadata: enforce id / full_name /
    type / tier on current and future editions so a mapping fix self-corrects
    in the data. Past editions keep their historical values."""
    if year < CFG_ENFORCE_FROM:
        if not merged.get("id"):
            merged["id"] = f"{target['slug']}{year % 100:02d}"
        merged.setdefault("full_name", target["full_name"])
        merged.setdefault("type", target.get("type", "conference"))
        if target.get("tier") and not merged.get("tier"):
            merged["tier"] = target["tier"]
        return
    merged["id"] = f"{target['slug']}{year % 100:02d}"
    merged["full_name"] = target["full_name"]
    merged["type"] = target.get("type", "conference")
    if str(merged.get("tier", "")).upper() in ("TBA", "TBD"):
        merged.pop("tier", None)  # placeholder, not a curated tier
    if target.get("tier"):
        merged["tier"] = target["tier"]


def apply_manual_override(merged, man):
    """Copy every override field manual.yml sets into the generated record;
    a field EXPLICITLY set to null deletes it (for values fabricated
    upstream, e.g. an abstract deadline the official CFP does not have).
    Returns the fields whose value materially changed."""
    changed = []
    for field in MANUAL_FIELDS:
        if field not in man:
            continue
        value = man[field]
        if value is None:
            if canon_record({field: merged.get(field)}):
                changed.append(field)
            merged.pop(field, None)
            continue
        if canon_record({field: merged.get(field)}) != canon_record({field: value}):
            changed.append(field)
        merged[field] = value
    if man.get("date") and not (man.get("start") and man.get("end")):
        parsed = parse_date_range(man["date"])
        if parsed:
            merged["start"], merged["end"] = parsed
    return changed


def tba_metadata_fields(rec):
    """Descriptive fields still unset on a record that already has a concrete
    deadline.

    Such a record is invisible to every other watchlist reason - it is not a
    TBA cycle (it has a deadline), usually not within 45 days, and its note
    need not look stale - so nobody is ever asked to look up its city or
    dates. A venue real enough to have published a CFP is real enough for
    these to be findable.
    """
    return [f for f in ("place", "date", "timezone")
            if clean(rec.get(f)).upper() in ("", "TBA", "TBD")]


def audit_reasons_for_record(key, year, rec, manual_keys, disagreements,
                             deferred_audits, today=None):
    """Deterministic weekly reasons, including persistent prior-year retries."""
    today = today or TODAY
    horizon = today + dt.timedelta(days=45)
    concrete = [d for d in (parse_dl_date(v) for v in as_list(rec.get("deadline")))
                if d is not None]
    relevant = not concrete or any(d >= today for d in concrete)
    reasons = []
    if (key, year) in deferred_audits:
        reasons.append("audit-deferred")
    if year >= today.year:
        reasons.append("scheduled-full-audit")
    if year >= today.year and not concrete:
        reasons.append("tba-upcoming-cycle")
    if any(today <= deadline <= horizon for deadline in concrete):
        reasons.append("deadline-within-45-days")
    if relevant and (key, year) in disagreements:
        reasons.append("cross-source-disagreement")
    if year >= today.year and rec.get("note") and STALE_NOTE_RE.search(str(rec["note"])):
        reasons.append("stale-placeholder-note")
    if relevant and (key, year) in manual_keys:
        reasons.append("manual-override-active")
    if relevant and year >= today.year and concrete and tba_metadata_fields(rec):
        reasons.append("tba-metadata")
    return reasons


def audit_record_rows(index, new_items, manual, manual_only_rows):
    """All rendered records, including rows that exist only in manual.yml."""
    rows = [(key, year, item["new_data"] or item["data"])
            for (key, year), item in sorted(index.items())]
    rows += [(it["record"]["title"], it["record"]["year"], it["record"])
             for it in new_items]
    rows += [(key, year, manual[(key, year)])
             for key, year in manual_only_rows]
    return rows


def missing_deferred_audits(deferred_audits, scheduled, by_key):
    """Retries with no current record/gap still need an explicit watch item."""
    return sorted(
        (key, year) for key, year in deferred_audits
        if (key, year) not in scheduled and key in by_key
        and FROM_YEAR <= year <= TO_YEAR
    )


def warn_manual_big_move(existing, merged, key, year):
    """The 90-day safety rail only guards against UPSTREAM: build_merged skips
    it entirely once manual.yml owns `deadline` because the weekly verifier
    and risk policy are the override's gate. Nothing here would otherwise
    report a large machine-written move, so retain a loud diagnostic."""
    if not existing:
        return
    old = [d for d in (parse_dl_date(v) for v in as_list(existing.get("deadline")))
           if d is not None]
    new = [d for d in (parse_dl_date(v) for v in as_list(merged.get("deadline")))
           if d is not None]
    if not old or not new:
        return
    shift = max(min(abs((n - o).days) for n in new) for o in old)
    if shift > SAFETY_RAIL_DAYS:
        warn(f"MANUAL OVERRIDE MOVED {key} {year} BY {shift} DAYS "
             f"({as_list(existing.get('deadline'))} -> {as_list(merged.get('deadline'))}); "
             "the safety rail does not apply to manual.yml - verify against the "
             "official page")


def manual_matches_upstream(man, cand):
    """True when upstream now agrees with every value manual.yml overrides -
    the entry is obsolete and can be removed.

    Two ways this must NOT say "obsolete", both of which it used to:

    * An entry that overrides only fields this function cannot compare
      (note / start / end) has nothing to check, and an empty check set is
      not agreement.
    * A field pinned to null exists precisely to SUPPRESS a value upstream
      fabricates. Upstream happening to omit that value on this run is what
      the override is for, not evidence it can go - the fabrication returns
      on the next sync.
    """
    checks = {
        "deadline": lambda: (canon_deadline_field(man.get("deadline"))
                             == canon_deadline_field(cand["deadlines"])),
        "abstract_deadline": lambda: (canon_deadline_field(man.get("abstract_deadline"))
                                      == canon_deadline_field(cand["abstracts"])),
        "timezone": lambda: canon_tz(man.get("timezone")) == canon_tz(cand.get("timezone")),
        "place": lambda: clean(man.get("place")) == clean(cand.get("place")),
        "date": lambda: clean(man.get("date")) == clean(cand.get("date")),
        "link": lambda: clean(man.get("link")) == clean(cand.get("link")),
    }
    overridden = [f for f in MANUAL_FIELDS if f in man]
    # A whole-entry deletion must not silently discard a note, derived range,
    # or explicit null that deterministic trackers cannot prove redundant.
    if any(f not in checks for f in overridden):
        return False
    comparable = [f for f in checks if f in man]
    if not comparable:
        return False
    if any(man.get(f) is None for f in overridden):
        return False
    return all(checks[f]() for f in comparable)


def agreement_basis_digest(man, candidates, target, failed_fetches):
    """Hash every trusted input that makes an override look removable."""
    candidate_rows = []
    for cand in sorted(candidates, key=lambda value: str(value.get("source", ""))):
        candidate_rows.append({
            "source": str(cand.get("source", "")),
            "values": canon_record({
                "deadline": cand.get("deadlines"),
                "abstract_deadline": cand.get("abstracts"),
                "timezone": cand.get("timezone"),
                "place": cand.get("place"),
                "date": cand.get("date"),
                "link": cand.get("link"),
            }),
        })
    payload = {
        "manual": canon_record({
            field: man[field] for field in MANUAL_FIELDS if field in man
        }),
        "configured_sources": list(target.get("priority", ())),
        "failed_sources": sorted(
            src for src in target.get("priority", ())
            if target["key"] in failed_fetches.get(src, set())
        ),
        "candidates": candidate_rows,
    }
    encoded = json.dumps(
        payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")
    return "sha256:" + hashlib.sha256(encoded).hexdigest()


def upstream_agreement_marker(man, candidates, target, failed_fetches):
    """Trusted watchlist evidence for retiring an obsolete manual override.

    A model cannot assert this flag. It is derived from parsed machine sources
    before the immutable watchlist artifact is uploaded. Every configured
    source fetch must be healthy, at least one source must cover the edition,
    and every covering candidate must agree with all comparable manual fields.
    """
    key = target["key"]
    complete = all(key not in failed_fetches.get(src, set())
                   for src in target.get("priority", ()))
    sources = sorted({str(c.get("source")) for c in candidates if c.get("source")})
    agrees = bool(complete and candidates
                  and all(manual_matches_upstream(man, cand) for cand in candidates))
    return {
        "agrees": agrees,
        "sources": sources,
        "all_fetches_healthy": complete,
        "basis_digest": agreement_basis_digest(
            man, candidates, target, failed_fetches
        ),
    }


def maybe_clear_stale_note(merged, existing, key, year):
    """Placeholder notes ('CFP not announced yet', ...) are cleared the moment
    the record gains its first concrete deadline."""
    note = merged.get("note")
    if not existing or not note:
        return
    had = bool(canon_deadline_field(existing.get("deadline")))
    has = bool(canon_deadline_field(merged.get("deadline")))
    if not had and has and STALE_NOTE_RE.search(str(note)):
        warn(f"{key} {year}: dropped stale placeholder note ({note!r})")
        merged.pop("note", None)


TZ_ASSUMED_NOTE = ("Timezone not stated by the official page; AoE assumed, "
                   "which is the CFP convention.")


def default_timezone(merged):
    """A record with a concrete deadline always carries an explicit timezone.

    AoE is the CFP convention when a page states none, and it is already what
    gets rendered - deadline-tracker.js does `String(timezone || 'UTC-12')`.
    Leaving the field absent or TBA does not avoid the assumption, it only
    hides it: an implicit default is indistinguishable from an oversight, so
    nobody can audit the data and a reader cannot tell "AoE by convention" from
    "nobody checked". Writing it down changes no rendered instant and makes the
    assumption reviewable.

    A TBA deadline gets no timezone: there is no instant to place in a zone.
    """
    if clean(merged.get("timezone")).upper() in ("TBA", "TBD"):
        merged.pop("timezone", None)
    if merged.get("timezone"):
        return
    concrete = [d for d in as_list(merged.get("deadline"))
                if d is not None and str(d).upper() not in ("TBA", "TBD")]
    if not concrete:
        return
    merged["timezone"] = "AoE"
    note = clean(merged.get("note"))
    if TZ_ASSUMED_NOTE not in note:
        merged["note"] = (note + " " + TZ_ASSUMED_NOTE).strip() if note else TZ_ASSUMED_NOTE


def build_merged(target, year, existing, cand, owned=frozenset()):
    """Apply the merge policy; `owned` names the fields a manual.yml override
    controls - upstream never touches those. Returns (merged_record, railed)."""
    merged = dict(existing) if existing else {}
    merged["title"] = target["key"]
    merged["year"] = year
    railed = "deadline" not in owned and rail_triggered(existing, cand["deadlines"])
    if railed:
        degrade(f"SAFETY RAIL {target['key']} {year}: upstream ({cand['source']}) would move a "
                f"future deadline by > {SAFETY_RAIL_DAYS} days "
                f"({as_list(existing.get('deadline'))} -> {cand['deadlines']}); "
                "existing record kept untouched pending the weekly official-source audit")
    else:
        for field in ("link", "place", "date"):
            if cand.get(field) and field not in owned:
                merged[field] = cand[field]
        if (existing and cand.get("date") and "date" not in owned
                and clean(existing.get("date")).upper() not in ("", "TBA")):
            old_range, new_range = parse_date_range(existing["date"]), parse_date_range(cand["date"])
            if old_range and new_range and old_range != new_range:
                warn(f"CONFERENCE DATE CHANGED {target['key']} {year}: "
                     f"{existing['date']!r} -> {cand['date']!r} (source {cand['source']}) "
                     "- verify against the official page; override in manual.yml if upstream is wrong")
        if cand.get("date") and "date" not in owned:
            # Keep start/end consistent with the (upstream-won) date string -
            # and never let stale values sit next to a CHANGED date they may
            # contradict. An unchanged-but-unparsable date keeps its start/end.
            parsed = parse_date_range(cand["date"])
            if parsed:
                merged["start"], merged["end"] = parsed
            elif clean(cand["date"]) != clean((existing or {}).get("date")):
                merged.pop("start", None)
                merged.pop("end", None)
        if "deadline" not in owned:
            merged["deadline"] = (cand["deadlines"][0] if len(cand["deadlines"]) == 1
                                  else list(cand["deadlines"]))
            if any(cand["abstracts"]) and "abstract_deadline" not in owned:
                abstracts = (cand["abstracts"] + [None] * len(cand["deadlines"]))[:len(cand["deadlines"])]
                merged["abstract_deadline"] = abstracts[0] if len(abstracts) == 1 else abstracts
            # else: the existing abstract_deadline (if any) stays untouched
        if ("timezone" not in owned and cand.get("timezone")
                and canon_tz(cand["timezone"]) != canon_tz(merged.get("timezone"))):
            merged["timezone"] = cand["timezone"]
    merged["deadline"] = norm_kept_deadlines(merged.get("deadline"))
    merged["abstract_deadline"] = norm_kept_deadlines(merged.get("abstract_deadline"))
    if merged["abstract_deadline"] is None:
        merged.pop("abstract_deadline")
    merged.pop("tba", None)  # legacy flag: meaningless once a record has real data
    default_timezone(merged)
    enforce_cfg_fields(merged, target, year)
    return merged, railed


def validate(rec, canonical_keys, require_deadline=True):
    errors = []
    if rec.get("title") not in canonical_keys:
        errors.append(f"title {rec.get('title')!r} is not a canonical key")
    year = rec.get("year")
    if not isinstance(year, int) or isinstance(year, bool) or not FROM_YEAR <= year <= TO_YEAR:
        errors.append(f"year {year!r} outside {FROM_YEAR}..{TO_YEAR}")
    def is_tba(value):
        return str(value).upper() in ("TBA", "TBD")

    # "TBA" is the established placeholder convention in this dataset (the
    # frontend renders it as a TBA row) - tolerated wherever a concrete
    # deadline is not required.
    for field in ("deadline", "abstract_deadline"):
        value = rec.get(field)
        if value is not None and not isinstance(value, (str, list)):
            errors.append(f"bad {field} type {type(value).__name__}")
        if isinstance(value, list) and (not value or len(value) > 8):
            errors.append(f"bad {field} cycle count {len(value)}")
        if isinstance(value, list) and any(
                item is not None and not isinstance(item, str) for item in value):
            errors.append(f"bad {field} cycle type")
    for field in ("timezone", "place", "date", "link", "note"):
        if rec.get(field) is not None and not isinstance(rec.get(field), str):
            errors.append(f"bad {field} type {type(rec.get(field)).__name__}")

    concrete = [d for d in as_list(rec.get("deadline"))
                if isinstance(d, str) and not is_tba(d)]
    if not concrete and require_deadline:
        errors.append("no concrete deadline")
    errors += [f"bad deadline {d!r}" for d in concrete if not valid_deadline(d)]
    errors += [f"bad abstract_deadline {a!r}" for a in as_list(rec.get("abstract_deadline"))
               if isinstance(a, str) and not is_tba(a) and not valid_deadline(a)]
    tz = rec.get("timezone")
    if isinstance(tz, str) and not is_tba(tz):
        if not TIMEZONE_RE.match(tz):
            errors.append(f"bad timezone {tz!r}")
        elif not tz_resolvable(tz):
            errors.append(f"unresolvable timezone {tz!r} (renders as AoE on the page)")
    link = rec.get("link")
    if isinstance(link, str) and not re.match(r"^https?://", link):
        errors.append(f"bad link {link!r}")
    return errors


# ---------------------------------------------------------------------- emission

def yaml_quote(value) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_scalar(key, value) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, (dt.datetime, dt.date)):
        return value.strftime("%Y-%m-%d")
    s = str(value)
    if key in ("id", "link", "timezone", "start", "end", "type"):
        return s
    if key == "tier" and re.fullmatch(r"T\d", s):
        return s
    return yaml_quote(s)


def render_record(rec) -> str:
    keys = [k for k in FIELD_ORDER if k in rec] + [k for k in rec if k not in FIELD_ORDER]
    lines = []
    for key in keys:
        value = rec[key]
        if value is None:
            continue
        prefix = "- " if not lines else "  "
        if key in ("deadline", "abstract_deadline") and isinstance(value, list):
            lines.append(f"{prefix}{key}:")
            lines += ["    - " + ("null" if item is None else yaml_quote(item)) for item in value]
        else:
            lines.append(f"{prefix}{key}: {render_scalar(key, value)}")
    return "\n".join(lines)


def assemble_file(items) -> str:
    blocks = sorted(items, key=lambda it: str(it["sort_title"]))
    return HEADER + "\n" + "\n\n".join(b["text"] for b in blocks) + "\n"


# -------------------------------------------------------------------------- main

def load_config():
    cfg = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    targets = cfg["conferences"]
    default_priority = (cfg.get("defaults") or {}).get("source_priority") or ["secdl", "ccfddl"]
    for target in targets:
        sources = target.get("sources")
        target["manual_only"] = sources == "manual-only"
        target["sources"] = sources if isinstance(sources, dict) else {}
        priority = target.get("source_priority") or default_priority
        target["priority"] = [s for s in priority if s in target["sources"]]
    return targets


def fetch_upstream(targets):
    """-> ({source: {key: {year: candidate}}}, failed, status_lines, any_source_ok).

    `failed` maps source name -> set of target keys whose fetch from that source
    FAILED (network/parse error), as opposed to succeeded-but-has-no-record.
    The merge loop must never fall back past a failed higher-priority source:
    stale lower-priority data would clobber values the failed source owns.
    """
    data = {"ccfddl": {}, "secdl": {}}
    failed = {"ccfddl": set(), "secdl": set()}
    status = []

    ccfddl_targets = [t for t in targets if "ccfddl" in t["sources"]]
    ok = 0
    for target in ccfddl_targets:
        path = target["sources"]["ccfddl"]
        url = CCFDDL_RAW + urllib.parse.quote(path)
        try:
            doc = yaml.safe_load(http_get(url))
            data["ccfddl"][target["key"]] = convert_ccfddl(doc, target["key"])
            ok += 1
        except Exception as exc:  # noqa: BLE001
            failed["ccfddl"].add(target["key"])
            degrade(f"ccfddl fetch failed for {target['key']} ({path}): {exc}")
    status.append(f"ccfddl: {ok}/{len(ccfddl_targets)} conference files fetched")
    ccfddl_ok = ok > 0

    secdl_ok = False
    try:
        records = yaml.safe_load(http_get(SECDL_RAW))
        if not isinstance(records, list):
            raise RuntimeError("unexpected structure (not a list)")
        secdl_targets = [target for target in targets if "secdl" in target["sources"]]
        parsed = 0
        for target in secdl_targets:
            try:
                data["secdl"][target["key"]] = convert_secdl(
                    records, target["sources"]["secdl"], target["key"])
                parsed += 1
            except Exception as exc:  # noqa: BLE001 - isolate one bad mapping/record
                failed["secdl"].add(target["key"])
                degrade(f"secdl parse failed for {target['key']}: {exc}")
        status.append(f"secdl: {parsed}/{len(secdl_targets)} targets parsed "
                      f"({len(records)} records fetched)")
        secdl_ok = True
    except Exception as exc:  # noqa: BLE001
        failed["secdl"] = {t["key"] for t in targets if "secdl" in t["sources"]}
        degrade(f"secdl fetch failed: {exc}")
        status.append("secdl: FAILED")

    return data, failed, status, (ccfddl_ok or secdl_ok)


def edition_is_past(*cands):
    """True when every concrete deadline across the candidates has passed -
    the edition is frozen history and not worth a recurring warning."""
    dates = [d for c in cands for d in (parse_dl_date(v) for v in c["deadlines"]) if d]
    return bool(dates) and all(d < TODAY for d in dates)


def sources_disagree(a, b):
    """True if two candidates for the same edition differ materially (> 1 day on
    any cycle, or a different cycle count). 1-day tolerance absorbs equivalent
    instants encoded in different timezones (e.g. AoE vs UTC)."""
    da = sorted(d for d in (parse_dl_date(v) for v in a["deadlines"]) if d)
    db = sorted(d for d in (parse_dl_date(v) for v in b["deadlines"]) if d)
    if len(da) != len(db):
        return True
    return any(abs((x - y).days) > 1 for x, y in zip(da, db))


def cross_fill_abstracts(winner, others):
    """Adopt the losing source's abstract deadlines when cycles line up exactly."""
    if any(winner["abstracts"]):
        return
    for other in others:
        if (len(other["deadlines"]) == len(winner["deadlines"]) and any(other["abstracts"])
                and all(o[:10] == w[:10] for o, w in zip(other["deadlines"], winner["deadlines"]))):
            winner["abstracts"] = list(other["abstracts"])
            return


def describe_changes(old, new):
    changes = []
    for key in sorted(set(old) | set(new)):
        if old.get(key) != new.get(key):
            changes.append(f"{key}: {old.get(key)!r} -> {new.get(key)!r}")
    return changes


def main() -> int:
    # Data and summaries contain non-ASCII (venue names); never let a legacy
    # console encoding (e.g. cp949) crash the run.
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--dry-run", action="store_true",
                        help="print the would-be changes without writing files")
    parser.add_argument("--watchlist", metavar="FILE",
                        help="also write a JSON audit watchlist of records worth "
                             "verifying against official sources (written even "
                             "with --dry-run; it is an audit artifact, not data)")
    args = parser.parse_args()

    try:
        targets = load_config()
    except Exception as exc:  # noqa: BLE001
        print(f"FATAL: cannot load {CONFIG_PATH}: {exc}")
        return 1
    canonical_keys = {t["key"] for t in targets}
    by_key = {t["key"]: t for t in targets}

    upstream, failed_fetches, fetch_status, any_ok = fetch_upstream(targets)
    if not any_ok:
        print("\n".join(fetch_status))
        print("FATAL: every upstream source failed; nothing written.")
        return 1

    files = load_existing()
    manual = load_manual(targets)
    try:
        deferred_audits = AS.retry_identities(AS.load())
    except AS.StateError as exc:
        degrade(f"persistent audit state is unusable: {exc}")
        deferred_audits = set()

    # Index existing records by (canonical key, edition year) and re-file any
    # record sitting in the wrong year/category bucket (conferences.yml owns
    # the category; the record's own year field owns the year).
    index = {}
    for (year, cat), entry in files.items():
        for item in entry["items"]:
            rec = item["data"]
            target = match_target(rec.get("title") or rec.get("name"), targets)
            rec_year = rec.get("year") if isinstance(rec.get("year"), int) else year
            item["bucket"] = (year, cat)
            item["target_key"] = target["key"] if target else None
            if target:
                home = (rec_year, target["category"])
                if home != (year, cat):
                    if home in files and not files[home].get("broken"):
                        warn(f"{target['key']} {rec_year}: re-filed from "
                             f"{year}/{cat}.yml into {home[0]}/{home[1]}.yml")
                        item["bucket"] = home
                    else:
                        warn(f"{target['key']} {rec_year}: belongs in "
                             f"{rec_year}/{target['category']}.yml but that file is "
                             "unavailable; left in place")
                if (target["key"], rec_year) in index:
                    degrade(f"duplicate record for {target['key']} {rec_year} in repo data; "
                            "only the first copy is auto-updated")
                else:
                    index[(target["key"], rec_year)] = item

    # Merge upstream candidates into existing records / create new ones.
    new_items = []
    kept, updated, created = [], [], []
    candidate_done = set()
    disagreements = set()
    upstream_agreements = {}
    upstream_link_candidates = {}
    for target in targets:
        # Never fall back past a source whose FETCH failed (vs. has no record):
        # its stale lower-priority sibling must not clobber data it owns.
        usable = []
        for src in target["priority"]:
            if target["key"] in failed_fetches.get(src, set()):
                if usable or len(target["priority"]) > 1:
                    warn(f"{target['key']}: source '{src}' unavailable this run; "
                         "not falling back to lower-priority sources (existing data kept)")
                break
            usable.append(src)
        per_source = {src: upstream.get(src, {}).get(target["key"], {}) for src in usable}
        years = sorted({y for cands in per_source.values() for y in cands})
        for year in years:
            ordered = [per_source[src][year] for src in usable if year in per_source[src]]
            link_candidates = [
                {"source": str(candidate.get("source")),
                 "link": clean(candidate.get("link"))}
                for candidate in ordered
                if candidate.get("source") and re.match(
                    r"^https?://", clean(candidate.get("link")), re.I
                )
            ]
            if link_candidates:
                upstream_link_candidates[(target["key"], year)] = link_candidates
            winner = dict(ordered[0])
            for other in ordered[1:]:
                if sources_disagree(winner, other):
                    disagreements.add((target["key"], year))
                    # Past editions are frozen history: the disagreement stays
                    # visible in the watchlist machinery but no longer clutters
                    # every run summary.
                    if not edition_is_past(winner, other):
                        warn(f"CROSS-SOURCE DISAGREEMENT {target['key']} {year}: "
                             f"{winner['source']}={winner['deadlines']} vs "
                             f"{other['source']}={other['deadlines']}; using {winner['source']} "
                             "- verify against the official CFP")
            cross_fill_abstracts(winner, ordered[1:])
            item = index.get((target["key"], year))
            existing = item["data"] if item else None
            man = manual.get((target["key"], year))
            owned = frozenset(f for f in MANUAL_FIELDS if man and f in man)
            merged, railed = build_merged(target, year, existing, winner, owned)
            if man is None or man.get("note") is None:
                maybe_clear_stale_note(merged, existing, target["key"], year)
            if man is not None:
                upstream_agreements[(target["key"], year)] = upstream_agreement_marker(
                    man, ordered, target, failed_fetches)
                if manual_matches_upstream(man, winner):
                    warn(f"manual.yml override for {target['key']} {year} matches "
                         "upstream now; the entry can be removed")
                changed_fields = apply_manual_override(merged, man)
                if changed_fields:
                    warn(f"manual override applied for {target['key']} {year}: "
                         + ", ".join(changed_fields))
                warn_manual_big_move(existing, merged, target["key"], year)
            errors = validate(merged, canonical_keys)
            if errors:
                degrade(f"validation failed for {target['key']} {year} "
                        f"({'; '.join(errors)}); kept existing entry" if existing
                        else f"validation failed for new {target['key']} {year} "
                             f"({'; '.join(errors)}); record dropped")
                continue
            candidate_done.add((target["key"], year))
            if existing is not None:
                if canon_record(merged) == canon_record(existing):
                    kept.append(f"{target['key']} {year}")
                else:
                    item["new_data"] = merged
                    changes = describe_changes(canon_record(existing), canon_record(merged))
                    label = " [RAILED]" if railed else ""
                    updated.append(f"{target['key']} {year} ({winner['source']}){label}: "
                                   + "; ".join(changes))
            else:
                created.append(f"{target['key']} {year} ({winner['source']}) -> "
                               f"{year}/{target['category']}.yml")
                new_items.append({"bucket": (year, target["category"]),
                                  "record": merged, "sort_title": merged["title"]})

    # Records with no upstream candidate this run still get cfg-field
    # normalization and manual overrides applied (they would otherwise
    # round-trip byte-for-byte and never self-correct).
    for (key, year), item in sorted(index.items()):
        if item["new_data"] is not None or (key, year) in candidate_done:
            continue
        target = by_key[key]
        existing = item["data"]
        merged = dict(existing)
        merged["title"] = key
        merged["year"] = year
        merged["deadline"] = norm_kept_deadlines(merged.get("deadline"))
        merged["abstract_deadline"] = norm_kept_deadlines(merged.get("abstract_deadline"))
        if merged["abstract_deadline"] is None:
            merged.pop("abstract_deadline")
        default_timezone(merged)
        enforce_cfg_fields(merged, target, year)
        man = manual.get((key, year))
        if man is not None:
            changed_fields = apply_manual_override(merged, man)
            if changed_fields:
                warn(f"manual override applied for {key} {year}: "
                     + ", ".join(changed_fields))
            warn_manual_big_move(existing, merged, key, year)
            if man.get("note") is None:
                maybe_clear_stale_note(merged, existing, key, year)
        if canon_record(merged) == canon_record(existing):
            continue
        errors = validate(merged, canonical_keys, require_deadline=False)
        if errors:
            degrade(f"validation failed for normalized {key} {year} "
                    f"({'; '.join(errors)}); kept existing entry")
            continue
        item["new_data"] = merged
        updated.append(f"{key} {year} (normalized/manual): "
                       + "; ".join(describe_changes(canon_record(existing),
                                                    canon_record(merged))))

    # Existing matched records with no upstream candidate are implicitly kept.
    for (key, year), item in sorted(index.items()):
        if item["new_data"] is None and f"{key} {year}" not in kept:
            has_candidate = any(year in upstream.get(src, {}).get(key, {})
                                for src in ("ccfddl", "secdl"))
            if not has_candidate:
                kept.append(f"{key} {year} (no upstream)")

    # manual.yml entries that match neither an existing record nor an upstream
    # candidate never reach a generated file - both merge loops skip them - so
    # they never pass validate() either. But the frontend fetches manual.yml
    # DIRECTLY at priority 0 (deadline-tracker.js), so such an entry still
    # renders on the live page. Unvalidated. Validate them here or nothing does.
    emitted = set(index) | {(it["record"]["title"], it["record"]["year"])
                            for it in new_items}
    manual_only_rows = sorted(set(manual) - emitted)
    for key, year in manual_only_rows:
        errors = validate(manual[(key, year)], canonical_keys)
        if errors:
            degrade(f"manual.yml-only row {key} {year} is invalid "
                    f"({'; '.join(errors)}); it reaches the page via manual.yml "
                    "even though it is in no generated file - fix or remove it")
        else:
            warn(f"{key} {year}: rendered from manual.yml only (no generated "
                 "record); it is not covered by the data files")

    # Coverage: every target should have some record for the upcoming cycle
    # year, or it silently never appears on the page (manual-only venues are
    # exactly the ones nobody notices going missing). A manual.yml-only row
    # counts as covered - it does render - or the gap warning and its
    # coverage-gap watchlist entry would never clear once filled that way.
    next_year = TODAY.year + 1
    covered = {key for (key, year) in index if year >= next_year}
    covered |= {it["record"]["title"] for it in new_items
                if it["record"]["year"] >= next_year}
    covered |= {key for (key, year) in manual if year >= next_year}
    gap_targets = []
    for target in targets:
        if target["key"] not in covered:
            gap_targets.append(target["key"])
            hint = ("manual-only source; waiting for the weekly official-source audit"
                    if target.get("manual_only") else "no upstream edition yet")
            warn(f"coverage gap: {target['key']} has no {next_year} entry ({hint})")

    # Audit watchlist: every current/future edition is scheduled for the weekly
    # official-source pass, with urgent data-quality reasons sorted first.  Full
    # scheduling is deliberate: if a correction is deferred while a stored
    # deadline is near, that identity must not disappear merely because the
    # old (possibly wrong) deadline passes before the next run.
    if args.watchlist:
        watchlist = []
        final_records = audit_record_rows(
            index, new_items, manual, manual_only_rows
        )
        for key, year, rec in final_records:
            reasons = audit_reasons_for_record(
                key, year, rec, set(manual), disagreements, deferred_audits)
            if reasons:
                watch_item = {
                    "title": key, "year": year,
                    "category": by_key[key]["category"],
                    "file": (None if (key, year) in manual_only_rows else
                             f"deadlines/data/conferences/{year}/{by_key[key]['category']}.yml"),
                    "reasons": reasons,
                    "record": {f: (str(rec[f]) if isinstance(rec.get(f), (dt.date, dt.datetime))
                                   else rec.get(f))
                               for f in ("deadline", "abstract_deadline", "timezone",
                                          "place", "date", "link", "note")
                                if rec.get(f) is not None},
                }
                if (key, year) in upstream_agreements:
                    watch_item["upstream_agreement"] = upstream_agreements[(key, year)]
                if (key, year) in upstream_link_candidates:
                    watch_item["upstream_link_candidates"] = \
                        upstream_link_candidates[(key, year)]
                watchlist.append(watch_item)
        for key in gap_targets:
            gap_identity = (key, next_year)
            reasons = ["coverage-gap"]
            if gap_identity in deferred_audits:
                reasons.append("audit-deferred")
            watchlist.append({"title": key, "year": next_year,
                              "category": by_key[key]["category"], "file": None,
                              "reasons": reasons, "record": {}})
        scheduled = {(item["title"], item["year"]) for item in watchlist}
        for key, year in missing_deferred_audits(
                deferred_audits, scheduled, by_key):
            watchlist.append({"title": key, "year": year,
                              "category": by_key[key]["category"], "file": None,
                              "reasons": ["audit-deferred"], "record": {}})
        # Sort by AUDITOR.md's own priority order, not alphabetically. The
        # workflow shards the complete list and requires every shard, while
        # this ordering still puts the highest-stakes records in the earliest
        # shard and therefore gives them the first retry opportunity.
        rank = {r: i for i, r in enumerate(
            ["deadline-within-45-days", "audit-deferred", "tba-upcoming-cycle",
             "manual-override-active",
             "cross-source-disagreement", "stale-placeholder-note", "coverage-gap",
             "tba-metadata", "scheduled-full-audit"])}
        watchlist.sort(key=lambda it: (min(rank.get(r, 99) for r in it["reasons"]),
                                       it["title"], it["year"]))
        Path(args.watchlist).write_text(
            json.dumps(watchlist, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    # Assemble output files (records land in their computed bucket, so a
    # re-filed record moves between files atomically in the same run).
    bucket_items = {}
    for entry in files.values():
        for item in entry["items"]:
            bucket_items.setdefault(item["bucket"], []).append(item)
    results = []  # (path, old_text, new_text)
    for (year, cat), entry in sorted(files.items()):
        if entry.get("broken"):
            continue
        blocks = []
        for item in bucket_items.get((year, cat), []):
            rec = item["new_data"] or item["data"]
            if item["new_data"] is not None or item["raw"] is None:
                text = render_record(rec)
            else:
                text = item["raw"]  # byte-level round-trip for untouched records
            blocks.append({"text": text, "sort_title": rec.get("title") or ""})
        for item in new_items:
            if item["bucket"] == (year, cat):
                blocks.append({"text": render_record(item["record"]),
                               "sort_title": item["sort_title"]})
        if not blocks:
            if entry["text"] is not None:
                # Every record moved elsewhere: leave a valid empty list so
                # the frontend fetch still parses.
                new_text = HEADER + "\n[]\n"
                if new_text != entry["text"]:
                    results.append((entry["path"], entry["text"], new_text))
            continue  # never create empty files
        new_text = assemble_file(blocks)
        if new_text != entry["text"]:
            results.append((entry["path"], entry["text"], new_text))

    # ------------------------------------------------------------------ summary
    print("== Fetch status ==")
    print("\n".join(fetch_status))
    print(f"\n== Actions ({FROM_YEAR}..{TO_YEAR}) ==")
    for line in created:
        print(f"  new      {line}")
    for line in updated:
        print(f"  updated  {line}")
    print(f"  kept     {len(kept)}: {', '.join(sorted(kept))}")
    if warnings:
        print("\n== Warnings ==")
        for line in warnings:
            print(f"  {line}")
    print("\n== Files ==")
    if not results:
        print("  no file changes")
    for path, old_text, new_text in results:
        rel = path.relative_to(REPO_ROOT)
        state = "create" if old_text is None else "update"
        if args.dry_run:
            print(f"  would {state} {rel} ({len(new_text.splitlines())} lines)")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            tmp = path.with_name(path.name + ".tmp")
            tmp.write_text(new_text, encoding="utf-8")
            os.replace(tmp, path)  # atomic: a crash mid-write can't truncate live data
            print(f"  {state}d {rel} ({len(new_text.splitlines())} lines)")
    if args.watchlist:
        print(f"\n== Watchlist ==\n  {len(watchlist)} record(s) -> {args.watchlist}")
    if health:
        print(f"\nHEALTH: DEGRADED - {len(health)} issue(s) marked [!] above "
              "remain queued for automatic retry or infrastructure alerting (exit 2)")
    else:
        print("\nHEALTH: ok")
    if args.dry_run:
        print("\n(dry run: nothing was written)")
    return 2 if health else 0


if __name__ == "__main__":
    sys.exit(main())
